"use client";
import { useState } from "react";

type CheckoutResult={razorpay_payment_id:string;razorpay_order_id:string;razorpay_signature:string};
type RazorpayOptions={key:string;amount:number;currency:string;name:string;description:string;order_id:string;prefill:Record<string,string>;theme:Record<string,string>;handler:(result:CheckoutResult)=>void;modal:{ondismiss:()=>void}};
declare global{interface Window{Razorpay:new(options:RazorpayOptions)=>{open:()=>void;on:(event:string,callback:(data:{error?:{description?:string}})=>void)=>void}}}
async function loadCheckout(){if(window.Razorpay)return true;return new Promise<boolean>(resolve=>{const existing=document.querySelector<HTMLScriptElement>('script[src="https://checkout.razorpay.com/v1/checkout.js"]');if(existing){existing.addEventListener("load",()=>resolve(true),{once:true});existing.addEventListener("error",()=>resolve(false),{once:true});return}const script=document.createElement("script");script.src="https://checkout.razorpay.com/v1/checkout.js";script.async=true;script.onload=()=>resolve(true);script.onerror=()=>resolve(false);document.head.appendChild(script)})}

export default function EnrollButton({courseId,price}:{courseId:number;price:number}){const[busy,setBusy]=useState(false),[message,setMessage]=useState("");async function freeEnrollment(){const r=await fetch("/api/courses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({courseId})}),d=await r.json();if(r.status===401){window.location.href="/client/login";return}if(r.ok){setMessage("You are enrolled. Opening your learning dashboard…");setTimeout(()=>window.location.href="/learning",900)}else{setMessage(d.error||"Unable to enroll.");setBusy(false)}}async function paidEnrollment(){const loaded=await loadCheckout();if(!loaded){setMessage("Secure checkout could not load. Please check your connection and try again.");setBusy(false);return}const r=await fetch("/api/payments/razorpay/order",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({courseId})}),d=await r.json();if(r.status===401){window.location.href="/client/login";return}if(!r.ok){setMessage(d.error||"Unable to start payment.");setBusy(false);return}const checkout=new window.Razorpay({key:d.keyId,amount:d.amount,currency:d.currency,name:"Attri Academy",description:d.courseTitle,order_id:d.orderId,prefill:d.prefill,theme:{color:"#ed7a22",backdrop_color:"#180e23"},modal:{ondismiss:()=>{setMessage("Payment window closed. Your pending enrollment is saved.");setBusy(false)}},handler:async(result)=>{setMessage("Verifying payment securely…");const verify=await fetch("/api/payments/razorpay/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(result)}),confirmation=await verify.json();if(verify.ok&&!confirmation.pending){setMessage("Payment successful. Opening your course…");setTimeout(()=>window.location.href="/learning",900)}else{setMessage(confirmation.message||confirmation.error||"Payment is awaiting confirmation.");setBusy(false)}}});checkout.on("payment.failed",data=>{setMessage(data.error?.description||"Payment was not completed. You can try again.");setBusy(false)});checkout.open()}
async function enroll(){setBusy(true);setMessage("");if(price)await paidEnrollment();else await freeEnrollment()}
return <div className="course-enroll-action"><button onClick={enroll} disabled={busy}>{busy?"Please wait…":price?"Pay securely with Razorpay →":"Start free course →"}</button>{price?<div className="razorpay-trust"><span>UPI</span><span>Cards</span><span>Net Banking</span><span>Wallets</span></div>:null}{message&&<p>{message}</p>}<small>Secure payment · Verified User account required · Access activates after confirmed payment.</small></div>}
