import { notFound } from "next/navigation";
import type { Metadata } from "next";
import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";
import { learningDb } from "../../learning-data";
import EnrollButton from "./EnrollButton";

async function course(slug:string){const db=await learningDb();return db.prepare("SELECT id,title,slug,category,level,mode,duration,description,price,lessons,image_url AS imageUrl,instructor,certificate,meta_title AS metaTitle,meta_description AS metaDescription FROM courses WHERE slug=? AND status='published'").bind(slug).first<Record<string,unknown>>()}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const c=await course((await params).slug);return c?{title:String(c.metaTitle||`${c.title} | Attri Academy`),description:String(c.metaDescription||c.description)}:{title:"Course not found"}}
export const dynamic="force-dynamic";
export default async function CoursePage({params}:{params:Promise<{slug:string}>}){const c=await course((await params).slug);if(!c)notFound();const db=await learningDb();const [sections,lessons]=await Promise.all([db.prepare("SELECT id,title,sort_order AS sortOrder FROM course_sections WHERE course_id=? ORDER BY sort_order,id").bind(c.id).all<Record<string,unknown>>(),db.prepare("SELECT id,section_id AS sectionId,title,lesson_type AS lessonType,duration_minutes AS durationMinutes,is_preview AS isPreview FROM course_lessons WHERE course_id=? AND status='published' ORDER BY sort_order,id").bind(c.id).all<Record<string,unknown>>()]);const price=Number(c.price);const money=price?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(price/100):"Free";return <main className="course-detail-page"><SiteHeader active="/courses"/><section className="course-detail-hero"><div><p>{String(c.category).toUpperCase()} · {String(c.level).toUpperCase()}</p><h1>{String(c.title)}</h1><span>{String(c.description)}</span><div><b>{String(c.duration)}</b><b>{String(c.mode)}</b><b>{String(c.lessons)} lessons</b>{Number(c.certificate)?<b>Certificate</b>:null}</div></div><aside><small>PROGRAMME FEE</small><strong>{money}</strong><span>Instructor: {String(c.instructor)}</span><EnrollButton courseId={Number(c.id)} price={price}/></aside></section><section className="course-detail-body"><div><p>CURRICULUM</p><h2>What you will learn</h2></div><div className="public-curriculum">{sections.results.length?sections.results.map((s,i)=><section key={String(s.id)}><header><span>{String(i+1).padStart(2,"0")}</span><h3>{String(s.title)}</h3><small>{lessons.results.filter(l=>l.sectionId===s.id).length} lessons</small></header>{lessons.results.filter(l=>l.sectionId===s.id).map(l=><article key={String(l.id)}><span>{l.lessonType==="video"?"▶":"◇"}</span><b>{String(l.title)}</b><small>{String(l.durationMinutes)} min{Number(l.isPreview)?" · Free preview":""}</small></article>)}</section>):<div className="curriculum-coming"><b>Curriculum publishing in progress</b><span>The detailed module plan will appear here shortly.</span></div>}</div></section><SiteFooter/></main>}
