import{getChatGPTUser}from"../../../chatgpt-auth";
async function db(){return(await import("cloudflare:workers")).env.DB}
async function owner(){return(await getChatGPTUser())?.email.toLowerCase()==="attriassociates99@gmail.com"}
const core=[
 ["cms_pages","CMS Pages"],["leads","CRM Leads"],["customer_profiles","Customers"],["projects","Projects"],["project_milestones","Milestones"],
 ["appointments","Appointments"],["products","Products"],["orders","Orders"],["courses","Courses"],["enrollments","Enrollments"],
 ["invoices","Invoices"],["payment_records","Payments"],["client_reports","Reports"],["certificates","Certificates"],["support_tickets","Tickets"],
 ["client_files","Files"],["staff_members","Staff"],["branches","Branches"],["service_catalog","Services"],["testimonials","Testimonials"],
 ["faqs","FAQs"],["notifications","Notifications"],["workflow_tasks","Tasks"],["audit_logs","Audit Logs"],["site_settings","Settings"]
] as const;
async function init(){const d=await db();await d.batch([
 d.prepare(`CREATE TABLE IF NOT EXISTS customer_profiles (id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT NOT NULL UNIQUE,full_name TEXT NOT NULL,phone TEXT NOT NULL DEFAULT '',company TEXT NOT NULL DEFAULT '',address TEXT NOT NULL DEFAULT '',city TEXT NOT NULL DEFAULT '',state TEXT NOT NULL DEFAULT '',pincode TEXT NOT NULL DEFAULT '',gstin TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS staff_members (id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT NOT NULL UNIQUE,full_name TEXT NOT NULL,phone TEXT NOT NULL DEFAULT '',role TEXT NOT NULL,department TEXT NOT NULL,permissions_json TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS branches (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,city TEXT NOT NULL,address TEXT NOT NULL,phone TEXT NOT NULL DEFAULT '',email TEXT NOT NULL DEFAULT '',map_url TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS service_catalog (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,category TEXT NOT NULL,summary TEXT NOT NULL DEFAULT '',base_price INTEGER NOT NULL DEFAULT 0,duration TEXT NOT NULL DEFAULT '',delivery_mode TEXT NOT NULL DEFAULT 'Online + On-site',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS testimonials (id INTEGER PRIMARY KEY AUTOINCREMENT,client_name TEXT NOT NULL,designation TEXT NOT NULL DEFAULT '',location TEXT NOT NULL DEFAULT '',quote TEXT NOT NULL,rating INTEGER NOT NULL DEFAULT 5,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS faqs (id INTEGER PRIMARY KEY AUTOINCREMENT,question TEXT NOT NULL,answer TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'General',sort_order INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'published',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS project_milestones (id INTEGER PRIMARY KEY AUTOINCREMENT,project_id INTEGER NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',due_date TEXT NOT NULL,completion INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY AUTOINCREMENT,recipient_email TEXT NOT NULL,channel TEXT NOT NULL DEFAULT 'email',subject TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',scheduled_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,sent_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT,actor_email TEXT NOT NULL,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL DEFAULT '',details_json TEXT NOT NULL DEFAULT '{}',ip_address TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS site_settings (id INTEGER PRIMARY KEY AUTOINCREMENT,setting_key TEXT NOT NULL UNIQUE,setting_value TEXT NOT NULL DEFAULT '',value_type TEXT NOT NULL DEFAULT 'text',is_public INTEGER NOT NULL DEFAULT 0,updated_by TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`)
]);await d.prepare("INSERT OR IGNORE INTO site_settings (setting_key,setting_value,value_type,is_public,updated_by) VALUES ('business_name','Attri Associates & Vastu Consultants','text',1,'system')").run()}
export async function GET(){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});await init();const d=await db();const tables=await Promise.all(core.map(async([table,label])=>{const row=await d.prepare(`SELECT COUNT(*) AS count FROM ${table}`).first<{count:number}>();return{table,label,count:Number(row?.count||0)}}));const totalRecords=tables.reduce((sum,x)=>sum+x.count,0);const latest=await d.prepare("SELECT actor_email AS actorEmail,action,entity_type AS entityType,created_at AS createdAt FROM audit_logs ORDER BY created_at DESC LIMIT 8").all();return Response.json({engine:"Cloudflare D1 / SQLite",status:"healthy",tables,totalTables:tables.length,totalRecords,latestAudit:latest.results,storage:{structured:"D1",files:"R2",migrations:"Drizzle"}})}
