"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Staff = { id: number; fullName: string; email: string; phone: string; role: string; department: string; permissionsJson: string; status: string };
type Data = { business: Record<string, string>; razorpay: Record<string, string>; staff: Staff[]; permissions: string[] };
const tabs = ["Business profile", "Razorpay", "Team access"] as const;
const labels: Record<string, string> = { dashboard: "Dashboard", crm: "CRM & leads", projects: "Projects", appointments: "Appointments", commerce: "Orders & shop", courses: "Courses", finance: "Finance", reports: "Reports", content: "Content", files: "File vault", analytics: "Analytics", settings: "Settings" };

export default function SettingsCenter() {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Business profile");
  const [data, setData] = useState<Data | null>(null);
  const [message, setMessage] = useState("");
  const [member, setMember] = useState<Partial<Staff> & { permissions: string[] }>({ role: "Operations manager", department: "Administration", status: "active", permissions: ["dashboard"] });
  async function load() { const response = await fetch("/api/admin/settings"); if (response.ok) setData(await response.json()); else setMessage("Unable to load settings."); }
  useEffect(() => { void load(); }, []);
  async function save(event: FormEvent<HTMLFormElement>, kind: "business" | "razorpay") { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>; const response = await fetch("/api/admin/settings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind, values }) }); const result = await response.json(); setMessage(response.ok ? "Settings saved securely." : result.error); if (response.ok) void load(); }
  async function saveMember(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/admin/settings", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind: "member", member }) }); const result = await response.json(); setMessage(response.ok ? "Team access record saved." : result.error); if (response.ok) { setMember({ role: "Operations manager", department: "Administration", status: "active", permissions: ["dashboard"] }); void load(); } }
  const activePermissions = useMemo(() => new Set(member.permissions), [member.permissions]);
  function edit(staff: Staff) { setTab("Team access"); setMember({ ...staff, permissions: JSON.parse(staff.permissionsJson || "[]") }); }
  if (!data) return <section className="admin-panel settings-loading">Loading settings…</section>;
  const business = data.business;
  return <section className="admin-panel settings-centre" id="settings"><div className="settings-hero"><div><p>CONTROL CENTRE / SETTINGS</p><h2>Configure with confidence.</h2><span>Business identity, payment credentials, and operational access in one protected workspace.</span></div><b>PRIVATE SETTINGS</b></div><div className="settings-tabs" role="tablist">{tabs.map(item => <button key={item} type="button" role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>{message ? <div className="settings-message" role="status">{message}<button onClick={() => setMessage("")} aria-label="Dismiss">×</button></div> : null}
    {tab === "Business profile" ? <form className="settings-form" onSubmit={event => save(event, "business")}><div className="settings-section-heading"><div><p>STORE PROFILE</p><h3>Public business details</h3><span>Used as the canonical operating details across your store and communications.</span></div></div><div className="settings-grid"><label>Display name<input name="business_name" defaultValue={business.business_name || "Attri Associates & Vastu Consultants"} required /></label><label>Legal business name<input name="business_legal_name" defaultValue={business.business_legal_name} /></label><label>Support mobile<input name="business_phone" type="tel" defaultValue={business.business_phone} /></label><label>Support email<input name="business_email" type="email" defaultValue={business.business_email} /></label><label className="wide">Registered address<textarea name="business_address" rows={3} defaultValue={business.business_address} /></label><label>City<input name="business_city" defaultValue={business.business_city} /></label><label>State<input name="business_state" defaultValue={business.business_state} /></label><label>PIN code<input name="business_pincode" defaultValue={business.business_pincode} /></label><label>Country<input name="business_country" defaultValue={business.business_country || "India"} /></label><label>GSTIN<input name="business_gstin" defaultValue={business.business_gstin} /></label><label>Business hours<input name="business_hours" defaultValue={business.business_hours} placeholder="Mon–Sat, 9:00 AM–6:00 PM" /></label><label>Currency<select name="business_currency" defaultValue={business.business_currency || "INR"}><option value="INR">INR — Indian Rupee</option><option value="USD">USD — US Dollar</option></select></label></div><button className="settings-save">Save business profile</button></form> : null}
    {tab === "Razorpay" ? <form className="settings-form" onSubmit={event => save(event, "razorpay")}><div className="settings-section-heading"><div><p>PAYMENT GATEWAY</p><h3>Razorpay credentials</h3><span>Credentials are stored server-side only and never returned to the browser in full.</span></div><b className="security-badge">SERVER-SIDE</b></div><div className="gateway-card"><div className="gateway-icon">R</div><div><b>Razorpay</b><small>{data.razorpay.razorpay_key_id ? "Connection details saved" : "Awaiting connection details"}</small></div><span>{data.razorpay.razorpay_key_id ? "Configured" : "Not configured"}</span></div><div className="settings-grid"><label>Key ID<input name="razorpay_key_id" defaultValue={data.razorpay.razorpay_key_id} placeholder="rzp_live_…" autoComplete="off" /></label><label>Key secret<input name="razorpay_key_secret" type="password" placeholder={data.razorpay.razorpay_key_secret ? "Saved — enter only to replace" : "Enter secret key"} autoComplete="new-password" /></label><label className="wide">Webhook secret<input name="razorpay_webhook_secret" type="password" placeholder={data.razorpay.razorpay_webhook_secret ? "Saved — enter only to replace" : "Enter webhook secret"} autoComplete="new-password" /></label></div><div className="settings-note">Keep live keys private. Use test keys until checkout has been verified end-to-end.</div><button className="settings-save">Save Razorpay details</button></form> : null}
    {tab === "Team access" ? <div className="team-settings"><div className="settings-section-heading"><div><p>ADMINISTRATION</p><h3>Users, roles & permissions</h3><span>Create an operational access roster and define the areas each team member may manage.</span></div></div><div className="access-notice">Owner sign-in remains protected by <code>ADMIN_EMAIL</code> and <code>ADMIN_PASSWORD</code>. Team permissions are saved now and will apply when multi-user admin sign-in is enabled.</div><div className="team-layout"><form className="settings-form team-form" onSubmit={saveMember}><h3>{member.id ? "Edit team member" : "Add team member"}</h3><div className="settings-grid"><label>Full name<input value={member.fullName || ""} onChange={event => setMember({ ...member, fullName: event.target.value })} required /></label><label>Email<input type="email" value={member.email || ""} onChange={event => setMember({ ...member, email: event.target.value })} required /></label><label>Mobile<input value={member.phone || ""} onChange={event => setMember({ ...member, phone: event.target.value })} /></label><label>Role<input value={member.role || ""} onChange={event => setMember({ ...member, role: event.target.value })} required /></label><label>Department<input value={member.department || ""} onChange={event => setMember({ ...member, department: event.target.value })} /></label><label>Status<select value={member.status || "active"} onChange={event => setMember({ ...member, status: event.target.value })}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><fieldset><legend>Module permissions</legend><div className="permission-pills">{data.permissions.map(permission => <label key={permission}><input type="checkbox" checked={activePermissions.has(permission)} onChange={() => setMember({ ...member, permissions: activePermissions.has(permission) ? member.permissions.filter(item => item !== permission) : [...member.permissions, permission] })} /><span>{labels[permission] || permission}</span></label>)}</div></fieldset><button className="settings-save">{member.id ? "Update access" : "Save team member"}</button></form><div className="team-list"><h3>Current roster <small>{data.staff.length}</small></h3>{data.staff.length ? data.staff.map(staff => <button type="button" className="member-card" key={staff.id} onClick={() => edit(staff)}><span>{staff.fullName.slice(0, 1).toUpperCase()}</span><div><b>{staff.fullName}</b><small>{staff.role} · {staff.email}</small></div><em className={staff.status}>{staff.status}</em></button>) : <div className="empty-team">No team members yet. Add the people who will manage operations.</div>}</div></div></div> : null}</section>;
}
