import{getChatGPTUser}from"../../../chatgpt-auth";
async function env(){return(await import("cloudflare:workers")).env}
async function owner(){return(await getChatGPTUser())?.email.toLowerCase()==="attriassociates99@gmail.com"}
async function init(){const{DB:d}=await env();await d.batch([
 d.prepare(`CREATE TABLE IF NOT EXISTS certificates (id INTEGER PRIMARY KEY AUTOINCREMENT,reference TEXT NOT NULL UNIQUE,student_name TEXT NOT NULL,student_email TEXT NOT NULL,course_title TEXT NOT NULL,issued_date TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'issued',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS payment_records (id INTEGER PRIMARY KEY AUTOINCREMENT,reference TEXT NOT NULL UNIQUE,customer_name TEXT NOT NULL,customer_email TEXT NOT NULL,purpose TEXT NOT NULL,gateway TEXT NOT NULL,transaction_id TEXT NOT NULL DEFAULT '',amount INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS workflow_tasks (id INTEGER PRIMARY KEY AUTOINCREMENT,reference TEXT NOT NULL UNIQUE,title TEXT NOT NULL,assignee TEXT NOT NULL,due_date TEXT NOT NULL,priority TEXT NOT NULL DEFAULT 'normal',status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS client_files (id INTEGER PRIMARY KEY AUTOINCREMENT,reference TEXT NOT NULL UNIQUE,customer_email TEXT NOT NULL,file_name TEXT NOT NULL,object_key TEXT NOT NULL UNIQUE,content_type TEXT NOT NULL,size INTEGER NOT NULL,category TEXT NOT NULL DEFAULT 'Project file',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`)
])}
export async function GET(){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});await init();const{DB:d}=await env();const[certificates,payments,tasks,files]=await Promise.all([
 d.prepare("SELECT id,reference,student_name AS studentName,student_email AS studentEmail,course_title AS courseTitle,issued_date AS issuedDate,status,created_at AS createdAt FROM certificates ORDER BY created_at DESC").all(),
 d.prepare("SELECT id,reference,customer_name AS customerName,customer_email AS customerEmail,purpose,gateway,transaction_id AS transactionId,amount,status,created_at AS createdAt FROM payment_records ORDER BY created_at DESC").all(),
 d.prepare("SELECT id,reference,title,assignee,due_date AS dueDate,priority,status,created_at AS createdAt FROM workflow_tasks ORDER BY due_date ASC").all(),
 d.prepare("SELECT id,reference,customer_email AS customerEmail,file_name AS fileName,content_type AS contentType,size,category,created_at AS createdAt FROM client_files ORDER BY created_at DESC").all()
]);return Response.json({certificates:certificates.results,payments:payments.results,tasks:tasks.results,files:files.results})}
export async function POST(request:Request){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});await init();const type=request.headers.get("content-type")||"";const e=await env();if(type.includes("multipart/form-data")){const f=await request.formData();const file=f.get("file");const email=String(f.get("customerEmail")||"").toLowerCase();const category=String(f.get("category")||"Project file");if(!(file instanceof File)||!email)return Response.json({error:"Choose a file and client email."},{status:400});if(file.size>20*1024*1024)return Response.json({error:"Maximum file size is 20 MB."},{status:400});const reference=`FIL-${Date.now().toString(36).toUpperCase()}`;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const key=`clients/${email}/${reference}-${safe}`;await e.BUCKET.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||"application/octet-stream"}});await e.DB.prepare("INSERT INTO client_files (reference,customer_email,file_name,object_key,content_type,size,category) VALUES (?,?,?,?,?,?,?)").bind(reference,email,file.name,key,file.type||"application/octet-stream",file.size,category).run();return Response.json({success:true,reference},{status:201})}
 const b=await request.json()as Record<string,string>;if(b.kind==="certificate"){if(!b.studentName||!b.studentEmail||!b.courseTitle||!b.issuedDate)return Response.json({error:"Complete certificate fields."},{status:400});const reference=`CERT-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;await e.DB.prepare("INSERT INTO certificates (reference,student_name,student_email,course_title,issued_date) VALUES (?,?,?,?,?)").bind(reference,b.studentName,b.studentEmail.toLowerCase(),b.courseTitle,b.issuedDate).run();return Response.json({success:true,reference},{status:201})}
 if(b.kind==="payment"){if(!b.customerName||!b.customerEmail||!b.purpose||!b.gateway||!b.amount)return Response.json({error:"Complete payment fields."},{status:400});const reference=`PAY-${Date.now().toString(36).toUpperCase()}`;await e.DB.prepare("INSERT INTO payment_records (reference,customer_name,customer_email,purpose,gateway,transaction_id,amount,status) VALUES (?,?,?,?,?,?,?,?)").bind(reference,b.customerName,b.customerEmail.toLowerCase(),b.purpose,b.gateway,b.transactionId||"",Math.round(Number(b.amount)*100),b.status||"pending").run();return Response.json({success:true,reference},{status:201})}
 if(b.kind==="task"){if(!b.title||!b.assignee||!b.dueDate)return Response.json({error:"Complete task fields."},{status:400});const reference=`TSK-${Date.now().toString(36).toUpperCase()}`;await e.DB.prepare("INSERT INTO workflow_tasks (reference,title,assignee,due_date,priority) VALUES (?,?,?,?,?)").bind(reference,b.title,b.assignee,b.dueDate,b.priority||"normal").run();return Response.json({success:true,reference},{status:201})}
 return Response.json({error:"Invalid operation."},{status:400})}
export async function PATCH(request:Request){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});await init();const b=await request.json()as{id?:number;kind?:string;status?:string};if(!b.id)return Response.json({error:"Record required."},{status:400});const{DB:d}=await env();const allowed:Record<string,string[]>={certificate:["issued","revoked"],payment:["pending","successful","failed","refunded"],task:["pending","in-progress","completed","cancelled"]};if(!b.kind||!b.status||!allowed[b.kind]?.includes(b.status))return Response.json({error:"Invalid status."},{status:400});const table=b.kind==="certificate"?"certificates":b.kind==="payment"?"payment_records":"workflow_tasks";await d.prepare(`UPDATE ${table} SET status=? WHERE id=?`).bind(b.status,b.id).run();return Response.json({success:true})}
