"use client";import{FormEvent,useEffect,useState}from"react";type Data={profile:{name:string;email:string};appointments:Array<Record<string,string>>;orders:Array<Record<string,string|number>>;enrollments:Array<Record<string,string|number>>;tickets:Array<Record<string,string>>};
export default function ClientPortal(){const[data,setData]=useState<Data|null>(null);const[tab,setTab]=useState("overview");const[msg,setMsg]=useState("");async function load(){const r=await fetch("/api/client");if(r.ok)setData(await r.json())}useEffect(()=>{void load()},[]);async function ticket(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const r=await fetch("/api/client",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const d=await r.json();setMsg(r.ok?`Ticket ${d.reference} created.`:d.error);if(r.ok){form.reset();await load()}}
 if(!data)return <div className="portal-loading">Loading your workspace…</div>;const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v/100);
 return <div className="portal-shell"><aside><a className="admin-logo" href="/"><span>A</span><div><b>ATTRI</b><small>CLIENT PORTAL</small></div></a><nav>{["overview","consultations","orders","learning","support"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><a className="portal-signout" href="/signout-with-chatgpt?return_to=/">Sign out</a></aside><main><header><div><p>CLIENT WORKSPACE</p><h1>Welcome, {data.profile.name.split(" ")[0]}.</h1></div><a href="/book-consultation">New consultation +</a></header>
 {tab==="overview"&&<><section className="portal-stats"><article><span>Consultations</span><strong>{data.appointments.length}</strong></article><article><span>Orders</span><strong>{data.orders.length}</strong></article><article><span>Courses</span><strong>{data.enrollments.length}</strong></article><article><span>Support tickets</span><strong>{data.tickets.length}</strong></article></section><section className="portal-welcome"><div><p>YOUR CONNECTED SPACE</p><h2>Everything related to your journey—together.</h2><span>Track consultations, purchases, learning and support from one secure dashboard.</span></div><div className="portal-actions"><a href="/book-consultation">Book consultation ↗</a><a href="/shop">Visit shop ↗</a><a href="/courses">Explore courses ↗</a></div></section></>}
 {tab==="consultations"&&<PortalList title="Your consultations" empty="No consultation records found." items={data.appointments.map(x=>({title:String(x.service),meta:`${x.preferredDate} · ${x.preferredTime}`,status:String(x.status),reference:String(x.reference)}))}/>}
 {tab==="orders"&&<PortalList title="Your orders" empty="No orders found." items={data.orders.map(x=>({title:money(Number(x.subtotal)),meta:String(x.paymentStatus),status:String(x.status),reference:String(x.reference)}))}/>}
 {tab==="learning"&&<PortalList title="Your learning" empty="No course enrollments found." items={data.enrollments.map(x=>({title:String(x.courseTitle),meta:`Progress ${x.progress}%`,status:String(x.status),reference:String(x.reference)}))}/>}
 {tab==="support"&&<section className="portal-support"><form onSubmit={ticket}><p>NEW SUPPORT TICKET</p><h2>How can we help?</h2><input name="subject" required placeholder="Subject"/><select name="category"><option>Consultation</option><option>Order</option><option>Course</option><option>Project</option><option>Technical support</option></select><select name="priority"><option>normal</option><option>high</option><option>urgent</option></select><textarea name="message" required rows={5} placeholder="Describe your question or issue"/><button>Submit ticket</button>{msg&&<small>{msg}</small>}</form><PortalList title="Your tickets" empty="No support tickets found." items={data.tickets.map(x=>({title:String(x.subject),meta:String(x.category),status:String(x.status),reference:String(x.reference)}))}/></section>}
 </main></div>}
function PortalList({title,empty,items}:{title:string;empty:string;items:Array<{title:string;meta:string;status:string;reference:string}>}){return <section className="portal-list"><p>RECORDS</p><h2>{title}</h2>{items.length===0?<div className="portal-empty">{empty}</div>:items.map(x=><article key={x.reference}><div><b>{x.title}</b><small>{x.reference} · {x.meta}</small></div><span>{x.status}</span></article>)}</section>}
