"use client";
import Link from "next/link";
import{useEffect,useState}from"react";
type Note={id:number;title:string;message:string;severity:string;actionUrl:string;createdAt:string;isRead:number};type Plan={name:string;amount:number;features:string[]};type Subscription={planName:string;status:string;reference:string;billingCycle:string};
export default function PortalTopActions({role}:{role:"user"|"consultant"}){const[panel,setPanel]=useState<"notifications"|"subscription"|null>(null);const[notes,setNotes]=useState<Note[]>([]);const[unread,setUnread]=useState(0);const[plans,setPlans]=useState<Plan[]>([]);const[current,setCurrent]=useState<Subscription|null>(null);const[cartCount,setCartCount]=useState(0);const[msg,setMsg]=useState("");
 async function loadNotes(){const r=await fetch("/api/notifications");if(r.ok){const d=await r.json();setNotes(d.notifications);setUnread(d.unread)}}async function loadPlans(){const r=await fetch("/api/subscriptions");if(r.ok){const d=await r.json();setPlans(d.plans);setCurrent(d.current)}}
 useEffect(()=>{const refresh=()=>{void loadNotes();void loadPlans();try{const c=JSON.parse(localStorage.getItem("attri-cart")||"{}") as Record<string,unknown>;setCartCount(Object.values(c).reduce<number>((total,value)=>total+Number(value),0))}catch{setCartCount(0)}};const timer=window.setTimeout(refresh,0);window.addEventListener("attri-cart",refresh);return()=>{window.clearTimeout(timer);window.removeEventListener("attri-cart",refresh)}},[]);
 async function read(id?:number){await fetch("/api/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(id?{id}:{all:true})});await loadNotes()}
 async function subscribe(planName:string){const r=await fetch("/api/subscriptions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({planName,billingCycle:"monthly"})});const d=await r.json();setMsg(r.ok?`${d.message} Reference: ${d.reference}`:d.error);if(r.ok)await loadPlans()}
 const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v/100);
 return <div className="portal-top-actions">{role==="user"&&<Link className="portal-icon" href="/shop?cart=open" aria-label={`Shopping cart with ${cartCount} items`} title="Shopping cart">🛒{cartCount>0&&<b>{cartCount}</b>}</Link>}<button className="portal-icon" onClick={()=>setPanel(panel==="notifications"?null:"notifications")} aria-label={`${unread} unread notifications`} title="Notifications">🔔{unread>0&&<b>{unread}</b>}</button><button className="portal-icon subscription-icon" onClick={()=>setPanel(panel==="subscription"?null:"subscription")} aria-label="Subscription" title="Subscription">♢</button>
 {panel&&<div className="portal-action-drawer"><button className="portal-drawer-close" onClick={()=>setPanel(null)} aria-label="Close panel">×</button>{panel==="notifications"?<><p>NOTIFICATION CENTRE</p><div className="drawer-heading"><h2>Updates & alerts</h2>{unread>0&&<button onClick={()=>read()}>Mark all read</button>}</div>{notes.length===0?<div className="portal-empty">You are all caught up.</div>:notes.map(n=><article className={`notification-card ${n.isRead?"read":""} severity-${n.severity}`} key={n.id} onClick={()=>read(n.id)}><span></span><div><b>{n.title}</b><small>{n.createdAt?.slice(0,10)}</small><p>{n.message}</p>{n.actionUrl.startsWith("/")&&<Link href={n.actionUrl}>Open →</Link>}</div></article>)}</>:<><p>MEMBERSHIP</p><h2>{current?"Your subscription":"Choose your plan"}</h2>{current&&<div className="current-plan"><b>{current.planName}</b><span>{current.status}</span><small>{current.reference} · {current.billingCycle}</small></div>}<div className="portal-plan-list">{plans.map(p=><article key={p.name}><div><b>{p.name}</b><strong>{money(p.amount)}<small>/month</small></strong></div><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><button disabled={current?.status==="pending"||current?.status==="active"} onClick={()=>subscribe(p.name)}>{current?.status==="pending"?"Request pending":current?.status==="active"?"Plan active":"Request subscription"}</button></article>)}</div>{msg&&<div className="subscription-message">{msg}</div>}</>}</div>}</div>}
