import{getChatGPTUser}from"../../../chatgpt-auth";
async function runtime(){return(await import("cloudflare:workers")).env}
async function owner(){return(await getChatGPTUser())?.email.toLowerCase()==="attriassociates99@gmail.com"}
export async function GET(){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});const e=await runtime();const d=e.DB;const[leads,appointments,orders,revenue,students,notifications,settings]=await Promise.all([
 d.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN status='won' THEN 1 ELSE 0 END) AS converted FROM leads").first(),
 d.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) AS completed FROM appointments").first(),
 d.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) AS completed FROM orders").first(),
 d.prepare("SELECT COALESCE(SUM(amount),0) AS total FROM payment_records WHERE status='successful'").first(),
 d.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN status IN ('active','completed') THEN 1 ELSE 0 END) AS active FROM enrollments").first(),
 d.prepare("SELECT id,recipient_email AS recipientEmail,channel,subject,status,scheduled_at AS scheduledAt FROM notifications ORDER BY created_at DESC LIMIT 30").all(),
 d.prepare("SELECT setting_key AS settingKey,setting_value AS settingValue FROM site_settings WHERE setting_key LIKE 'seo_%' OR setting_key LIKE 'tracking_%'").all()
]);const seo=Object.fromEntries((settings.results as Array<{settingKey:string;settingValue:string}>).map(x=>[x.settingKey,x.settingValue]));return Response.json({metrics:{leads,appointments,orders,revenue,students},notifications:notifications.results,seo,gateways:{razorpay:Boolean((e as Record<string,unknown>).RAZORPAY_KEY_ID),stripe:Boolean((e as Record<string,unknown>).STRIPE_SECRET_KEY),paypal:Boolean((e as Record<string,unknown>).PAYPAL_CLIENT_ID)}})}
export async function POST(request:Request){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});const b=await request.json()as Record<string,string>;const e=await runtime();const u=await getChatGPTUser();if(b.kind==="notification"){if(!b.recipientEmail||!b.subject||!b.message)return Response.json({error:"Complete notification fields."},{status:400});await e.DB.prepare("INSERT INTO notifications (recipient_email,channel,subject,message,status,scheduled_at) VALUES (?,?,?,?,?,?)").bind(b.recipientEmail.toLowerCase(),b.channel||"email",b.subject,b.message,"queued",b.scheduledAt||new Date().toISOString()).run();await e.DB.prepare("INSERT INTO audit_logs (actor_email,action,entity_type) VALUES (?,?,?)").bind(u?.email||"system","queued","notification").run();return Response.json({success:true},{status:201})}if(b.kind==="seo"){const entries=[["seo_default_title",b.defaultTitle||""],["seo_default_description",b.defaultDescription||""],["seo_google_verification",b.googleVerification||""],["tracking_ga4_id",b.ga4Id||""],["tracking_meta_pixel_id",b.metaPixelId||""],["tracking_linkedin_id",b.linkedinId||""]];await e.DB.batch(entries.map(([k,v])=>e.DB.prepare("INSERT INTO site_settings (setting_key,setting_value,value_type,is_public,updated_by) VALUES (?,?,?,0,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP").bind(k,v,"text",u?.email||"system")));return Response.json({success:true})}return Response.json({error:"Invalid request."},{status:400})}
