"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
type Product = { id: number; name: string; category: string; price: number; stock: number; status: string; imageUrl: string; itemType: string; deliveryMode?: string; sku?: string; hsnCode?: string };
type Category = { id: number; name: string; slug: string; status: string; sortOrder: number };
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
export default function ProductCatalogue({ initialProducts }: { initialProducts: Product[] }) {
  const [products, setProducts] = useState<Product[]>(initialProducts), [categories, setCategories] = useState<Category[]>([]), [query, setQuery] = useState(""), [category, setCategory] = useState("all"), [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/commerce", { cache: "no-store" }); if (!response.ok) { setMessage("Unable to load the product catalogue."); return; } const data = await response.json(); setProducts(data.products || []); setCategories(data.categories || []); }
  useEffect(() => { void load(); }, []);
  async function setStatus(product: Product, status: string) { const response = await fetch("/api/admin/commerce", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: product.id, kind: "product", status }) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? "Product visibility updated." : data.error || "Unable to update product."); if (response.ok) void load(); }
  async function deleteProduct(product: Product) { if (!window.confirm(`Delete ${product.name}? This cannot be undone.`)) return; const response = await fetch(`/api/admin/commerce?id=${product.id}&kind=product`, { method: "DELETE" }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? "Product deleted." : data.error || "Unable to delete product."); if (response.ok) void load(); }
  const visible = useMemo(() => products.filter(item => (category === "all" || item.category === category) && `${item.name} ${item.sku || ""} ${item.hsnCode || ""}`.toLowerCase().includes(query.toLowerCase())), [products, category, query]);
  return <section className="admin-panel product-catalogue-reference" id="products"><div className="product-reference-heading"><div><p>STORE / CATALOGUE</p><h2>Product catalogue</h2></div><Link href="/admin/products/new">＋ Add product</Link></div><div className="product-reference-toolbar"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search products, SKU or HSN code"/><select value={category} onChange={event => setCategory(event.target.value)}><option value="all">All categories</option>{categories.map(item => <option key={item.id} value={item.name}>{item.name}</option>)}</select><span>{visible.length} products</span><Link href="/admin?module=product-categories">Manage categories →</Link></div>{message && <div className="product-reference-message" role="status">{message}<button onClick={() => setMessage("")} aria-label="Dismiss">×</button></div>}<div className="product-reference-list">{visible.length ? visible.map(item => <article key={item.id} className="product-reference-row"><div className="product-reference-image">{item.imageUrl ? <Image unoptimized width={80} height={80} src={item.imageUrl} alt=""/> : <span>{item.name.slice(0, 1).toUpperCase()}</span>}</div><div className="product-reference-info"><strong>{item.name}</strong><small>{item.category || "Uncategorised"} · {item.itemType || "physical"} · {item.deliveryMode || "Online"}</small><em>{money.format(item.price / 100)} · {item.stock} stock/seats</em></div><div className="product-reference-actions"><select value={item.status} onChange={event => void setStatus(item, event.target.value)} aria-label={`Change ${item.name} status`}><option value="draft">Draft</option><option value="active">Published</option></select><Link href={`/admin/products/${item.id}/edit`}>Edit</Link><button className="product-delete-action" onClick={() => void deleteProduct(item)}>Delete</button></div></article>) : <p className="product-reference-empty">No products match your filters. Add your first product to begin.</p>}</div></section>;
}
