"use client";
import{FormEvent,useEffect,useState}from"react";
type Product={id:number;name:string;slug:string;category:string;description:string;price:number;stock:number;status:string;imageUrl:string;itemType:string;deliveryMode:string;specialPrice:number;specialFrom:string;specialTo:string;duration:string;classes:number;sortOrder:number;metaTitle:string;metaKeywords:string;metaDescription:string;serviceType:string;fulfillmentMode:string;sku:string;shortDescription:string;material:string;colour:string;dimensions:string;weight:string;placement:string;benefits:string;usageInstructions:string;careInstructions:string;gstRate:number;hsnCode:string};
const tabs=[["general","General"],["specifications","Specifications"],["guidance","Vastu Guidance"],["pricing","Pricing"],["inventory","Inventory"],["course","Course / Service"],["media","Media"],["visibility","Visibility"],["seo","SEO"]];
export default function ProductEditor({id}:{id?:number}){
 const[tab,setTab]=useState("general"),[product,setProduct]=useState<Product|null>(null),[itemType,setItemType]=useState("physical"),[message,setMessage]=useState(""),[busy,setBusy]=useState(Boolean(id));
 useEffect(()=>{if(!id)return;fetch("/api/admin/commerce").then(async r=>{const d=await r.json();const found=(d.products??[]).find((x:Product)=>x.id===id);if(found){setProduct(found);setItemType(found.itemType)}else setMessage("Product not found.");setBusy(false)})},[id]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/admin/commerce",{method:id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,...(id?{id,kind:"product"}:{})})});const d=await r.json();if(r.ok)window.location.href="/admin?module=products";else{setMessage(d.error||"Unable to save product.");setBusy(false)}}
 if(busy&&id&&!product)return <main className="catalog-editor-shell"><div className="editor-loading">Loading product editor…</div></main>;
 const p=product;
 return <main className="catalog-editor-shell">
  <header className="editor-topbar"><div><a href="/admin?module=products">← Products</a><p>STORE / PRODUCT CATALOGUE</p><h1>{id?"Edit product":"Add product"}</h1></div><a href="/shop" target="_blank">View shop ↗</a></header>
  {message&&<div className="editor-message">{message}</div>}
  <form className="catalog-editor" key={p?.id??"new"} onSubmit={save}>
   <nav className="editor-tabs" aria-label="Product form sections">{tabs.map(([key,label])=><button type="button" className={tab===key?"active":""} onClick={()=>setTab(key)} key={key}>{label}</button>)}</nav>
   <div className="editor-body">
    <section className={tab==="general"?"editor-panel active":"editor-panel"}><h2>General information</h2><p>Core product identity and customer-facing description.</p><div className="editor-grid"><label className="wide">Product name<input name="name" required defaultValue={p?.name}/></label><label>Item type<select name="itemType" value={itemType} onChange={e=>setItemType(e.target.value)}><option value="physical">Physical product</option><option value="digital">Digital product</option><option value="course">Course</option><option value="service">Service</option></select></label><label>Category<select name="category" defaultValue={p?.category||"Remedies"}><option>Tools</option><option>Remedies</option><option>Vastu Figurines</option><option>Energy &amp; Wellness</option><option>Symbols &amp; Yantras</option><option>Brahmasthan Remedies</option><option>Advanced Remedies</option><option>Elemental Strips</option><option>Yantras</option><option>Pyramids</option><option>Books</option><option>Software</option><option>Courses</option><option>Services</option><option>Reports</option><option>Consultation</option><option>Digital Downloads</option></select></label><label>Delivery type<select name="deliveryMode" defaultValue={p?.deliveryMode||"Online"}><option>Online</option><option>Offline</option><option>Online + Offline</option></select></label><label className="wide">Short description<textarea name="shortDescription" rows={3} defaultValue={p?.shortDescription}/></label><label className="wide">Full description<textarea name="description" rows={8} required defaultValue={p?.description}/></label></div></section>
    <section className={tab==="specifications"?"editor-panel active":"editor-panel"}><h2>Specifications</h2><p>Identifiers, physical attributes and tax information shown to customers.</p><div className="editor-grid"><label>SKU<input name="sku" defaultValue={p?.sku}/></label><label>Material<input name="material" defaultValue={p?.material}/></label><label>Colour / finish<input name="colour" defaultValue={p?.colour}/></label><label>Dimensions<input name="dimensions" defaultValue={p?.dimensions} placeholder="e.g. 20 × 10 × 18 cm"/></label><label>Weight<input name="weight" defaultValue={p?.weight} placeholder="e.g. 850 g"/></label><label>GST rate (%)<input name="gstRate" type="number" min="0" step="0.01" defaultValue={p?.gstRate??0}/></label><label>HSN code<input name="hsnCode" defaultValue={p?.hsnCode}/></label></div></section>
    <section className={tab==="guidance"?"editor-panel active":"editor-panel"}><h2>Vastu guidance</h2><p>Placement and care information supplied with the remedy.</p><div className="editor-grid"><label className="wide">Recommended placement<textarea name="placement" rows={4} defaultValue={p?.placement}/></label><label className="wide">Benefits<textarea name="benefits" rows={4} defaultValue={p?.benefits}/></label><label className="wide">Usage instructions<textarea name="usageInstructions" rows={4} defaultValue={p?.usageInstructions}/></label><label className="wide">Care instructions<textarea name="careInstructions" rows={4} defaultValue={p?.careInstructions}/></label></div></section>
    <section className={tab==="pricing"?"editor-panel active":"editor-panel"}><h2>Pricing</h2><p>Configure regular pricing and an optional scheduled offer.</p><div className="editor-grid"><label>Regular price (₹)<input name="price" type="number" min="0" step=".01" required defaultValue={p?p.price/100:""}/></label><label>Special price (₹)<input name="specialPrice" type="number" min="0" step=".01" defaultValue={p?.specialPrice?p.specialPrice/100:0}/></label><label>Offer starts<input name="specialFrom" type="date" defaultValue={p?.specialFrom}/></label><label>Offer ends<input name="specialTo" type="date" defaultValue={p?.specialTo}/></label></div></section>
    <section className={tab==="inventory"?"editor-panel active":"editor-panel"}><h2>Inventory & order</h2><p>Manage available stock or seats and storefront sequence.</p><div className="editor-grid"><label>Stock / seats<input name="stock" type="number" min="0" required defaultValue={p?.stock??0}/></label><label>Display order<input name="sortOrder" type="number" defaultValue={p?.sortOrder??0}/><small>Lower numbers appear first.</small></label></div></section>
    <section className={tab==="course"?"editor-panel active":"editor-panel"}><h2>Course or service details</h2><p>Additional fulfilment information based on the selected item type.</p>{itemType==="course"?<div className="editor-grid"><label>Duration<input name="duration" required defaultValue={p?.duration} placeholder="8 weeks"/></label><label>Number of classes<input name="classes" type="number" min="0" required defaultValue={p?.classes??0}/></label></div>:itemType==="service"?<div className="editor-grid"><label>Service type<select name="serviceType" defaultValue={p?.serviceType||"virtual"}><option value="virtual">Virtual product / service</option><option value="consultation">Consultation</option></select></label><label>Fulfilment mode<select name="fulfillmentMode" defaultValue={p?.fulfillmentMode||"Email"}><option>Email</option><option>Online meeting</option><option>WhatsApp</option><option>Phone call</option><option>Digital download</option><option>Client portal</option><option>Other online mode</option></select></label></div>:<div className="editor-note">Select “Course” or “Service” in General to enable these fields.</div>}</section>
    <section className={tab==="media"?"editor-panel active":"editor-panel"}><h2>Product media</h2><p>Add the primary image shown on product cards.</p><div className="editor-grid"><label className="wide">Product image URL<input name="imageUrl" type="url" defaultValue={p?.imageUrl} placeholder="https://..."/></label>{p?.imageUrl&&<img className="editor-image-preview" src={p.imageUrl} alt="Current product"/>}</div></section>
    <section className={tab==="visibility"?"editor-panel active":"editor-panel"}><h2>Publishing</h2><p>Control whether customers can see this product.</p><div className="editor-grid"><label>Status<select name="status" defaultValue={p?.status||"active"}><option value="active">Published — live in shop</option><option value="draft">Draft — hidden</option></select></label></div></section>
    <section className={tab==="seo"?"editor-panel active":"editor-panel"}><h2>Search engine optimization</h2><p>Set the product URL and search result information.</p><div className="editor-grid"><label className="wide">URL slug<div className="slug-input"><span>/shop/</span><input name="slug" defaultValue={p?.slug} placeholder="auto-created-from-product-name"/></div></label><label className="wide">Meta title<input name="metaTitle" maxLength={70} defaultValue={p?.metaTitle}/><small>Recommended: 50–60 characters.</small></label><label className="wide">Meta keywords<input name="metaKeywords" defaultValue={p?.metaKeywords} placeholder="vastu remedies, copper pyramid, energy balance"/></label><label className="wide">Meta description<textarea name="metaDescription" maxLength={170} rows={4} defaultValue={p?.metaDescription}/><small>Recommended: 140–160 characters.</small></label></div></section>
   </div>
   <footer className="editor-actions"><a href="/admin?module=products">Cancel</a><button disabled={busy}>{busy?"Saving…":id?"Save changes":"Create product"}</button></footer>
  </form>
 </main>
}
