"use client";
import { FormEvent, useEffect, useState } from "react";
type Category={id:number;name:string;slug:string;description:string;iconUrl:string;status:string;sortOrder:number};
const empty={name:"",description:"",iconUrl:"",status:"active",sortOrder:0};
export default function ProductCategories(){const[categories,setCategories]=useState<Category[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<number|null>(null),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/admin/commerce",{cache:"no-store"});if(r.ok){const d=await r.json();setCategories(d.categories||[])}else setMessage("Unable to load categories.")};useEffect(()=>{void load()},[]);
 async function save(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/commerce",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"category",...(editing?{id:editing}:{}),...form})});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage(d.error||"Unable to save category.");return}setMessage(editing?"Category updated.":"Category created.");setForm(empty);setEditing(null);void load()}
 function edit(item:Category){setEditing(item.id);setForm({name:item.name,description:item.description||"",iconUrl:item.iconUrl||"",status:item.status,sortOrder:item.sortOrder})}
 async function remove(item:Category){if(!window.confirm(`Delete ${item.name}?`))return;const r=await fetch(`/api/admin/commerce?id=${item.id}&kind=category`,{method:"DELETE"});const d=await r.json().catch(()=>({}));setMessage(r.ok?"Category deleted.":d.error||"Unable to delete category.");if(r.ok)void load()}
 return <section className="admin-panel product-categories-reference" id="product-categories"><div className="product-categories-heading"><div><p>STORE / CATALOGUE</p><h2>Product categories</h2><span>Organise products with reusable customer-facing taxonomy, imagery, SEO descriptions, and display order.</span></div></div><div className="product-categories-layout"><form onSubmit={save}><div className="category-form-tabs"><button type="button" className="active">General</button><button type="button">SEO</button></div><h3>{editing?"Edit category":"Add product category"}</h3><label>Category name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={4}/></label><label>Icon image URL<input type="url" value={form.iconUrl} onChange={e=>setForm({...form,iconUrl:e.target.value})} placeholder="PNG, JPG or WEBP URL"/><small>Use a square image for consistent category cards.</small></label><label>Display order<input type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>{message&&<div className="product-category-message" role="status">{message}</div>}<button className="product-category-save">{editing?"Update category":"Create category"}</button>{editing&&<button type="button" className="product-category-cancel" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel edit</button>}</form><div className="product-category-list">{categories.length?categories.map(item=><article key={item.id}><div className="product-category-icon">{item.iconUrl?<img src={item.iconUrl} alt=""/>:<b>{item.name.slice(0,1).toUpperCase()}</b>}</div><div className="product-category-copy"><strong>{item.name}</strong><small>/{item.slug} · Order {item.sortOrder}</small><em className={item.status}>{item.status}</em>{item.description&&<p>{item.description}</p>}</div><div className="product-category-actions"><button onClick={()=>edit(item)}>Edit</button><button className="danger" onClick={()=>void remove(item)}>Delete</button></div></article>):<p className="product-reference-empty">No categories yet.</p>}</div></div></section>}
