import{hasAdminModulePermission}from"../../../auth";
const modules=[
 ["overview","Overview","Dashboard"],["analytics","Analytics","Dashboard"],["notifications","Notifications","Dashboard"],
 ["leads","Leads & CRM","Customers & Delivery"],["appointments","Appointments","Customers & Delivery"],["projects","Projects","Customers & Delivery"],["reports","Reports","Customers & Delivery"],["support","Support Tickets","Customers & Delivery"],
 ["products","Products","Store & Academy"],["commerce","Orders","Store & Academy"],["courses","Courses","Store & Academy"],["learning","Students & LMS","Store & Academy"],["finance","Invoices","Store & Academy"],
 ["pages","Pages & CMS","Content & Marketing"],["media","Media Manager","Content & Marketing"],["seo-manager","SEO Manager","Content & Marketing"],
 ["operations","Operations","System & Administration"],["automation","Workflows","System & Administration"],["data-managers","Data Managers","System & Administration"],["database","Database","System & Administration"],["vault","File Vault","System & Administration"],["permissions","Team Access","System & Administration"],["settings","Settings & Integrations","System & Administration"]
] as const;
const moduleKeys=modules.map(x=>x[0]);
async function runtime(){return(await import("cloudflare:workers")).env}
async function owner(){return hasAdminModulePermission("permissions")}
async function initialise(){const d=(await runtime()).DB;await d.prepare("CREATE TABLE IF NOT EXISTS admin_roles (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE,description TEXT NOT NULL DEFAULT '',permissions_json TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();const count=await d.prepare("SELECT COUNT(*) AS total FROM admin_roles").first<{total:number}>();if(!count?.total){const presets=[
 ["Super Admin","Complete control of every backend module",moduleKeys],
 ["Architect","Projects, appointments, files and reports",["overview","appointments","projects","reports","media","vault"]],
 ["Vastu Expert","Consultations, projects, reports and client files",["overview","appointments","projects","reports","vault"]],
 ["Sales Team","Leads, appointments, products and orders",["overview","leads","appointments","products","commerce"]],
 ["Course Instructor","Courses, students, media and support",["overview","courses","learning","media","support"]],
 ["Accounts","Orders, invoices, reports and operations",["overview","commerce","finance","reports","operations"]]
 ] as const;for(const role of presets)await d.prepare("INSERT INTO admin_roles (name,description,permissions_json) VALUES (?,?,?)").bind(role[0],role[1],JSON.stringify(role[2])).run()}return d}
function cleanPermissions(value:unknown){return Array.isArray(value)?value.filter((x):x is string=>typeof x==="string"&&moduleKeys.includes(x as never)):[]}
const encoder=new TextEncoder();function hex(bytes:ArrayBuffer|Uint8Array){return Array.from(bytes instanceof Uint8Array?bytes:new Uint8Array(bytes),x=>x.toString(16).padStart(2,"0")).join("")}function random(size:number){const b=new Uint8Array(size);crypto.getRandomValues(b);return hex(b)}async function passwordHash(password:string,saltHex:string){const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const salt=Uint8Array.from(saltHex.match(/.{2}/g)||[],x=>Number.parseInt(x,16));return hex(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations:100000},key,256))}
export async function GET(){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});const d=await initialise();const[staff,roles]=await Promise.all([d.prepare("SELECT id,email,full_name AS fullName,role,department,permissions_json AS permissionsJson,status FROM staff_members ORDER BY full_name").all(),d.prepare("SELECT id,name,description,permissions_json AS permissionsJson,status FROM admin_roles ORDER BY id").all()]);return Response.json({staff:staff.results,roles:roles.results,modules:modules.map(([key,label,group])=>({key,label,group}))})}
export async function POST(request:Request){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});const b=await request.json()as Record<string,unknown>;const d=await initialise();if(b.action==="role"){const name=String(b.name||"").trim(),description=String(b.description||"").trim();if(name.length<2)return Response.json({error:"Enter a role name."},{status:400});await d.prepare("INSERT INTO admin_roles (name,description,permissions_json) VALUES (?,?,?)").bind(name,description,JSON.stringify(cleanPermissions(b.permissions))).run();return Response.json({success:true},{status:201})}if(b.action==="user"){const fullName=String(b.fullName||"").trim(),email=String(b.email||"").trim().toLowerCase(),role=String(b.role||"").trim(),department=String(b.department||"").trim(),password=String(b.password||"");if(fullName.length<2||!/^\S+@\S+\.\S+$/.test(email)||!role||!department)return Response.json({error:"Complete all administrator details."},{status:400});if(!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{10,}$/.test(password))return Response.json({error:"Temporary password needs 10+ characters, uppercase, lowercase and a number."},{status:400});const roleRow=await d.prepare("SELECT permissions_json AS permissionsJson FROM admin_roles WHERE name=? AND status='active'").bind(role).first<{permissionsJson:string}>();if(!roleRow)return Response.json({error:"Select an active role."},{status:400});const salt=random(16),hash=await passwordHash(password,salt);await d.batch([d.prepare("INSERT INTO auth_accounts (email,full_name,password_hash,password_salt,account_type,status) VALUES (?,?,?,?,'admin','active') ON CONFLICT(email) DO UPDATE SET full_name=excluded.full_name,password_hash=excluded.password_hash,password_salt=excluded.password_salt,account_type='admin',status='active',updated_at=CURRENT_TIMESTAMP").bind(email,fullName,hash,salt),d.prepare("INSERT INTO staff_members (email,full_name,phone,role,department,permissions_json,status) VALUES (?,?,?,?,?,?,'active') ON CONFLICT(email) DO UPDATE SET full_name=excluded.full_name,role=excluded.role,department=excluded.department,permissions_json=excluded.permissions_json,status='active'").bind(email,fullName,String(b.phone||""),role,department,roleRow.permissionsJson)]);return Response.json({success:true},{status:201})}return Response.json({error:"Invalid access-control action."},{status:400})}
export async function PATCH(request:Request){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});const b=await request.json()as Record<string,unknown>,d=await initialise();if(b.action==="role"){const id=Number(b.id);if(!id)return Response.json({error:"Invalid role."},{status:400});await d.prepare("UPDATE admin_roles SET permissions_json=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(JSON.stringify(cleanPermissions(b.permissions)),b.status==="inactive"?"inactive":"active",id).run();return Response.json({success:true})}if(b.action==="user"){const id=Number(b.id),role=String(b.role||""),status=b.status==="inactive"?"inactive":"active";const row=await d.prepare("SELECT email FROM staff_members WHERE id=?").bind(id).first<{email:string}>();const roleRow=await d.prepare("SELECT permissions_json AS permissionsJson FROM admin_roles WHERE name=?").bind(role).first<{permissionsJson:string}>();if(!row||!roleRow)return Response.json({error:"User or role not found."},{status:404});const permissions=b.useRoleDefaults===true?roleRow.permissionsJson:JSON.stringify(cleanPermissions(b.permissions));await d.batch([d.prepare("UPDATE staff_members SET role=?,permissions_json=?,status=? WHERE id=?").bind(role,permissions,status,id),d.prepare("UPDATE auth_accounts SET status=?,updated_at=CURRENT_TIMESTAMP WHERE lower(email)=?").bind(status,row.email.toLowerCase())]);return Response.json({success:true})}return Response.json({error:"Invalid update."},{status:400})}
export async function DELETE(request:Request){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});const url=new URL(request.url),type=url.searchParams.get("type"),id=Number(url.searchParams.get("id")),d=await initialise();if(!id)return Response.json({error:"Invalid record."},{status:400});if(type==="user"){const row=await d.prepare("SELECT email FROM staff_members WHERE id=?").bind(id).first<{email:string}>();if(row)await d.batch([d.prepare("DELETE FROM staff_members WHERE id=?").bind(id),d.prepare("DELETE FROM auth_sessions WHERE lower(email)=?").bind(row.email.toLowerCase()),d.prepare("DELETE FROM auth_accounts WHERE lower(email)=?").bind(row.email.toLowerCase())]);return Response.json({success:true})}if(type==="role"){const role=await d.prepare("SELECT name FROM admin_roles WHERE id=?").bind(id).first<{name:string}>();if(!role)return Response.json({error:"Role not found."},{status:404});const used=await d.prepare("SELECT COUNT(*) AS total FROM staff_members WHERE role=?").bind(role.name).first<{total:number}>();if(used?.total)return Response.json({error:"Move users to another role before deleting this role."},{status:409});await d.prepare("DELETE FROM admin_roles WHERE id=?").bind(id).run();return Response.json({success:true})}return Response.json({error:"Invalid record type."},{status:400})}
