import{getChatGPTUser}from"../../../chatgpt-auth";
async function db(){return(await import("cloudflare:workers")).env.DB}
async function owner(){return(await getChatGPTUser())?.email.toLowerCase()==="attriassociates99@gmail.com"}
const allowed=["customer","staff","branch","service","testimonial","faq"] as const;type Kind=typeof allowed[number];
function valid(value:unknown):value is Kind{return typeof value==="string"&&(allowed as readonly string[]).includes(value)}
const table:Record<Kind,string>={customer:"customer_profiles",staff:"staff_members",branch:"branches",service:"service_catalog",testimonial:"testimonials",faq:"faqs"};
async function audit(action:string,kind:Kind,id:string){const u=await getChatGPTUser();await(await db()).prepare("INSERT INTO audit_logs (actor_email,action,entity_type,entity_id) VALUES (?,?,?,?)").bind(u?.email||"system",action,kind,id).run()}
export async function GET(){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});const d=await db();const[customers,staff,branches,services,testimonials,faqs]=await Promise.all([d.prepare("SELECT id,email,full_name AS fullName,phone,company,city,state,gstin,status FROM customer_profiles ORDER BY created_at DESC").all(),d.prepare("SELECT id,email,full_name AS fullName,phone,role,department,status FROM staff_members ORDER BY created_at DESC").all(),d.prepare("SELECT id,name,city,address,phone,email,status FROM branches ORDER BY created_at DESC").all(),d.prepare("SELECT id,name,slug,category,summary,base_price AS basePrice,duration,delivery_mode AS deliveryMode,status FROM service_catalog ORDER BY created_at DESC").all(),d.prepare("SELECT id,client_name AS clientName,designation,location,quote,rating,status FROM testimonials ORDER BY created_at DESC").all(),d.prepare("SELECT id,question,answer,category,sort_order AS sortOrder,status FROM faqs ORDER BY sort_order,id").all()]);return Response.json({customers:customers.results,staff:staff.results,branches:branches.results,services:services.results,testimonials:testimonials.results,faqs:faqs.results})}
export async function POST(request:Request){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});const b=await request.json()as Record<string,string>;if(!valid(b.kind))return Response.json({error:"Invalid data type."},{status:400});const d=await db();let result;if(b.kind==="customer"){if(!b.fullName||!b.email)return Response.json({error:"Name and email are required."},{status:400});result=await d.prepare("INSERT INTO customer_profiles (email,full_name,phone,company,city,state,gstin) VALUES (?,?,?,?,?,?,?)").bind(b.email.toLowerCase(),b.fullName,b.phone||"",b.company||"",b.city||"",b.state||"",b.gstin||"").run()}else if(b.kind==="staff"){if(!b.fullName||!b.email||!b.role||!b.department)return Response.json({error:"Complete staff details."},{status:400});result=await d.prepare("INSERT INTO staff_members (email,full_name,phone,role,department) VALUES (?,?,?,?,?)").bind(b.email.toLowerCase(),b.fullName,b.phone||"",b.role,b.department).run()}else if(b.kind==="branch"){if(!b.name||!b.city||!b.address)return Response.json({error:"Branch name, city and address are required."},{status:400});result=await d.prepare("INSERT INTO branches (name,city,address,phone,email) VALUES (?,?,?,?,?)").bind(b.name,b.city,b.address,b.phone||"",b.email||"").run()}else if(b.kind==="service"){if(!b.name||!b.slug||!b.category)return Response.json({error:"Service name, slug and category are required."},{status:400});result=await d.prepare("INSERT INTO service_catalog (name,slug,category,summary,base_price,duration,delivery_mode) VALUES (?,?,?,?,?,?,?)").bind(b.name,b.slug.toLowerCase().replace(/[^a-z0-9-]/g,"-"),b.category,b.summary||"",Math.round(Number(b.basePrice||0)*100),b.duration||"",b.deliveryMode||"Online + On-site").run()}else if(b.kind==="testimonial"){if(!b.clientName||!b.quote)return Response.json({error:"Client name and testimonial are required."},{status:400});result=await d.prepare("INSERT INTO testimonials (client_name,designation,location,quote,rating) VALUES (?,?,?,?,?)").bind(b.clientName,b.designation||"",b.location||"",b.quote,Math.max(1,Math.min(5,Number(b.rating||5)))).run()}else{if(!b.question||!b.answer)return Response.json({error:"Question and answer are required."},{status:400});result=await d.prepare("INSERT INTO faqs (question,answer,category,sort_order) VALUES (?,?,?,?)").bind(b.question,b.answer,b.category||"General",Number(b.sortOrder||0)).run()}const id=String(result.meta.last_row_id||"");await audit("created",b.kind,id);return Response.json({success:true,id},{status:201})}
export async function PATCH(request:Request){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});const b=await request.json()as{kind?:string;id?:number;status?:string};if(!valid(b.kind)||!b.id||!b.status)return Response.json({error:"Invalid update."},{status:400});const statuses:Record<Kind,string[]>={customer:["active","inactive"],staff:["active","inactive"],branch:["active","inactive"],service:["active","inactive","draft"],testimonial:["pending","published","archived"],faq:["published","draft","archived"]};if(!statuses[b.kind].includes(b.status))return Response.json({error:"Invalid status."},{status:400});await(await db()).prepare(`UPDATE ${table[b.kind]} SET status=? WHERE id=?`).bind(b.status,b.id).run();await audit("status_updated",b.kind,String(b.id));return Response.json({success:true})}
export async function DELETE(request:Request){if(!await owner())return Response.json({error:"Unauthorized"},{status:401});const u=new URL(request.url);const kind=u.searchParams.get("kind");const id=Number(u.searchParams.get("id"));if(!valid(kind)||!id)return Response.json({error:"Invalid record."},{status:400});await(await db()).prepare(`DELETE FROM ${table[kind]} WHERE id=?`).bind(id).run();await audit("deleted",kind,String(id));return Response.json({success:true})}
