import{hasAdminModulePermission}from"../../../auth";
async function db(){return(await import("cloudflare:workers")).env.DB}async function allowed(){return hasAdminModulePermission("blog")}
function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,100)}
async function init(){const d=await db();await d.prepare("CREATE TABLE IF NOT EXISTS blog_posts (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,excerpt TEXT NOT NULL DEFAULT '',content TEXT NOT NULL DEFAULT '',category TEXT NOT NULL DEFAULT 'Vastu',tags TEXT NOT NULL DEFAULT '',author TEXT NOT NULL DEFAULT 'CE. SS Attri',cover_image_url TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',featured INTEGER NOT NULL DEFAULT 0,published_at TEXT NOT NULL DEFAULT '',reading_minutes INTEGER NOT NULL DEFAULT 5,meta_title TEXT NOT NULL DEFAULT '',meta_keywords TEXT NOT NULL DEFAULT '',meta_description TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();return d}
const select="id,title,slug,excerpt,content,category,tags,author,cover_image_url AS coverImageUrl,status,featured,published_at AS publishedAt,reading_minutes AS readingMinutes,meta_title AS metaTitle,meta_keywords AS metaKeywords,meta_description AS metaDescription,created_at AS createdAt,updated_at AS updatedAt";
export async function GET(){if(!await allowed())return Response.json({error:"Unauthorized"},{status:401});const rows=await(await init()).prepare(`SELECT ${select} FROM blog_posts ORDER BY featured DESC,CASE WHEN published_at='' THEN created_at ELSE published_at END DESC,id DESC`).all();return Response.json({posts:rows.results})}
function fields(b:Record<string,unknown>){const title=String(b.title||"").trim(),status=["published","scheduled","archived"].includes(String(b.status))?String(b.status):"draft";return[title,slugify(String(b.slug||title)),String(b.excerpt||"").trim(),String(b.content||"").trim(),String(b.category||"Vastu").trim(),String(b.tags||"").trim(),String(b.author||"CE. SS Attri").trim(),String(b.coverImageUrl||"").trim(),status,b.featured==="yes"?1:0,String(b.publishedAt||"").trim(),Math.max(1,Number(b.readingMinutes||5)),String(b.metaTitle||title).trim(),String(b.metaKeywords||b.tags||"").trim(),String(b.metaDescription||b.excerpt||"").trim()]as const}
export async function POST(r:Request){if(!await allowed())return Response.json({error:"Unauthorized"},{status:401});const b=await r.json()as Record<string,unknown>,v=fields(b);if(!v[0]||!v[1]||!v[3])return Response.json({error:"Title, URL and article content are required."},{status:400});try{await(await init()).prepare("INSERT INTO blog_posts (title,slug,excerpt,content,category,tags,author,cover_image_url,status,featured,published_at,reading_minutes,meta_title,meta_keywords,meta_description) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(...v).run();return Response.json({success:true},{status:201})}catch{return Response.json({error:"That article URL is already in use."},{status:409})}}
export async function PATCH(r:Request){if(!await allowed())return Response.json({error:"Unauthorized"},{status:401});const b=await r.json()as Record<string,unknown>,id=Number(b.id);if(!id)return Response.json({error:"Article required."},{status:400});const d=await init();if(!b.title){await d.prepare("UPDATE blog_posts SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(String(b.status),id).run();return Response.json({success:true})}const v=fields(b);try{await d.prepare("UPDATE blog_posts SET title=?,slug=?,excerpt=?,content=?,category=?,tags=?,author=?,cover_image_url=?,status=?,featured=?,published_at=?,reading_minutes=?,meta_title=?,meta_keywords=?,meta_description=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(...v,id).run();return Response.json({success:true})}catch{return Response.json({error:"That article URL is already in use."},{status:409})}}
export async function DELETE(r:Request){if(!await allowed())return Response.json({error:"Unauthorized"},{status:401});const id=Number(new URL(r.url).searchParams.get("id"));if(!id)return Response.json({error:"Article required."},{status:400});await(await init()).prepare("DELETE FROM blog_posts WHERE id=?").bind(id).run();return Response.json({success:true})}
