import {ensurePaymentTable} from "./razorpay";

export const consultationPackages=[
 {slug:"direction-call",name:"Quick Direction Call",price:99900,duration:30,summary:"Focused guidance for one clear Vastu or planning question.",modes:["Video Consultation","Phone Consultation"]},
 {slug:"scientific-vastu",name:"Scientific Vastu Consultation",price:249900,duration:60,summary:"Detailed discussion of your home, office or commercial space.",modes:["Video Consultation","Phone Consultation","Office Meeting"]},
 {slug:"plan-review",name:"Drawing & Plan Review",price:499900,duration:90,summary:"Structured review of an architectural drawing with implementation guidance.",modes:["Video Consultation","Office Meeting"]},
 {slug:"industrial-strategy",name:"Industrial Vastu Strategy",price:999900,duration:120,summary:"Senior consultation for factories, plants and complex industrial sites.",modes:["Video Consultation","Office Meeting","Site Visit"]},
] as const;

export async function ensureConsultationPayments(){const db=await ensurePaymentTable();await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS consultation_payment_attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,reference TEXT NOT NULL UNIQUE,appointment_id INTEGER NOT NULL,customer_email TEXT NOT NULL,amount INTEGER NOT NULL,razorpay_order_id TEXT NOT NULL UNIQUE,razorpay_payment_id TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'created',signature_verified INTEGER NOT NULL DEFAULT 0,failure_reason TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),
 db.prepare("CREATE INDEX IF NOT EXISTS consultation_payment_email_idx ON consultation_payment_attempts(customer_email,created_at)"),
]);const cols=await db.prepare("PRAGMA table_info(appointments)").all<{name:string}>();for(const[name,sql]of[["package_slug","ALTER TABLE appointments ADD COLUMN package_slug TEXT NOT NULL DEFAULT ''"],["amount","ALTER TABLE appointments ADD COLUMN amount INTEGER NOT NULL DEFAULT 0"],["duration_minutes","ALTER TABLE appointments ADD COLUMN duration_minutes INTEGER NOT NULL DEFAULT 60"],["meeting_url","ALTER TABLE appointments ADD COLUMN meeting_url TEXT NOT NULL DEFAULT ''"],["assigned_to","ALTER TABLE appointments ADD COLUMN assigned_to TEXT NOT NULL DEFAULT ''"],["admin_notes","ALTER TABLE appointments ADD COLUMN admin_notes TEXT NOT NULL DEFAULT ''"]])if(!cols.results.some(x=>x.name===name))await db.prepare(sql).run();return db}

export async function activateConsultation(orderId:string,paymentId:string,verified:number){const db=await ensureConsultationPayments();const a=await db.prepare("SELECT p.id,p.appointment_id AS appointmentId,p.customer_email AS email,p.amount,a.reference,a.name,a.service,a.preferred_date AS preferredDate,a.preferred_time AS preferredTime,a.payment_status AS paymentStatus FROM consultation_payment_attempts p JOIN appointments a ON a.id=p.appointment_id WHERE p.razorpay_order_id=? LIMIT 1").bind(orderId).first<{id:number;appointmentId:number;email:string;amount:number;reference:string;name:string;service:string;preferredDate:string;preferredTime:string;paymentStatus:string}>();if(!a)return false;if(a.paymentStatus==="paid")return true;const invoice=`INV-${a.reference.replace(/^AA-/,"")}`;await db.batch([
 db.prepare("UPDATE consultation_payment_attempts SET razorpay_payment_id=?,status='captured',signature_verified=MAX(signature_verified,?),failure_reason='',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(paymentId,verified,a.id),
 db.prepare("UPDATE appointments SET payment_status='paid',status='confirmed' WHERE id=?").bind(a.appointmentId),
 db.prepare("INSERT OR IGNORE INTO invoices(number,customer_name,customer_email,description,amount,tax_rate,status,due_date) VALUES (?,?,?,?,?,18,'paid',date('now'))").bind(invoice,a.name,a.email,`Consultation ${a.reference}: ${a.service}`,a.amount),
 db.prepare("INSERT INTO notifications(recipient_email,channel,subject,message,status) VALUES (?,'email',?,?, 'queued')").bind(a.email,`Consultation confirmed: ${a.reference}`,`${a.service} is confirmed for ${a.preferredDate} at ${a.preferredTime}. Invoice ${invoice} is available in your portal.`),
 db.prepare("INSERT INTO notifications(recipient_email,channel,subject,message,status) VALUES ('admin','dashboard',?,?, 'queued')").bind(`Paid consultation: ${a.reference}`,`${a.name} booked ${a.service} for ${a.preferredDate} at ${a.preferredTime}.`),
]);const exists=await db.prepare("SELECT id FROM payment_records WHERE transaction_id=?").bind(paymentId).first();if(!exists)await db.prepare("INSERT INTO payment_records(reference,customer_name,customer_email,purpose,gateway,transaction_id,amount,status) VALUES (?,?,?,?,?,?,?,'successful')").bind(`PAY-${Date.now().toString(36).toUpperCase()}`,a.name,a.email,`Consultation ${a.reference}`,"Razorpay",paymentId,a.amount).run();return true}
