import { learningDb } from "./learning-data";
import { readSecret } from "./secret-vault";

export type RazorpayRuntime={DB:D1Database;RAZORPAY_KEY_ID?:string;RAZORPAY_KEY_SECRET?:string;RAZORPAY_WEBHOOK_SECRET?:string};
export async function razorpayEnv(){const e=(await import("cloudflare:workers")).env as RazorpayRuntime;return{...e,RAZORPAY_KEY_ID:e.RAZORPAY_KEY_ID||await readSecret("RAZORPAY_KEY_ID"),RAZORPAY_KEY_SECRET:e.RAZORPAY_KEY_SECRET||await readSecret("RAZORPAY_KEY_SECRET"),RAZORPAY_WEBHOOK_SECRET:e.RAZORPAY_WEBHOOK_SECRET||await readSecret("RAZORPAY_WEBHOOK_SECRET")}}
export function configured(e:RazorpayRuntime){return Boolean(e.RAZORPAY_KEY_ID&&e.RAZORPAY_KEY_SECRET)}
function hex(bytes:ArrayBuffer){return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("")}
export async function hmac(value:string,secret:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return hex(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value)))}
export function equal(a:string,b:string){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
export async function razorpayFetch(path:string,e:RazorpayRuntime,init:RequestInit={}){const response=await fetch(`https://api.razorpay.com/v1${path}`,{...init,headers:{authorization:`Basic ${btoa(`${e.RAZORPAY_KEY_ID}:${e.RAZORPAY_KEY_SECRET}`)}`,"content-type":"application/json",...(init.headers||{})}});const data=await response.json()as Record<string,unknown>;if(!response.ok)throw new Error(String((data.error as Record<string,unknown>)?.description||"Razorpay request failed."));return data}
export async function ensurePaymentTable(){const db=await learningDb();await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS course_payment_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT,reference TEXT NOT NULL UNIQUE,enrollment_id INTEGER NOT NULL,course_id INTEGER NOT NULL,customer_email TEXT NOT NULL,amount INTEGER NOT NULL,currency TEXT NOT NULL DEFAULT 'INR',razorpay_order_id TEXT NOT NULL UNIQUE,razorpay_payment_id TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'created',signature_verified INTEGER NOT NULL DEFAULT 0,failure_reason TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),db.prepare("CREATE INDEX IF NOT EXISTS course_payment_email_idx ON course_payment_attempts(customer_email,created_at)")]);return db}
export async function activateOrder(orderId:string,paymentId:string,verified:number){const db=await ensurePaymentTable();const attempt=await db.prepare("SELECT p.id,p.reference,p.enrollment_id AS enrollmentId,p.course_id AS courseId,p.customer_email AS email,p.amount,e.student_name AS studentName,c.title AS courseTitle FROM course_payment_attempts p JOIN enrollments e ON e.id=p.enrollment_id JOIN courses c ON c.id=p.course_id WHERE p.razorpay_order_id=? LIMIT 1").bind(orderId).first<{id:number;reference:string;enrollmentId:number;courseId:number;email:string;amount:number;studentName:string;courseTitle:string}>();if(!attempt)return false;await db.batch([db.prepare("UPDATE course_payment_attempts SET razorpay_payment_id=?,status='captured',signature_verified=MAX(signature_verified,?),failure_reason='',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(paymentId,verified,attempt.id),db.prepare("UPDATE enrollments SET payment_status='successful',status='active' WHERE id=?").bind(attempt.enrollmentId)]);const existing=await db.prepare("SELECT id FROM payment_records WHERE transaction_id=? LIMIT 1").bind(paymentId).first();if(!existing)await db.prepare("INSERT INTO payment_records (reference,customer_name,customer_email,purpose,gateway,transaction_id,amount,status) VALUES (?,?,?,?,?,?,?,'successful')").bind(`PAY-${Date.now().toString(36).toUpperCase()}`,attempt.studentName,attempt.email,`Course: ${attempt.courseTitle}`,"Razorpay",paymentId,attempt.amount).run();return true}
