type Runtime={DB:D1Database;SETTINGS_ENCRYPTION_KEY?:string};
const allowed=new Set(["RAZORPAY_KEY_ID","RAZORPAY_KEY_SECRET","RAZORPAY_WEBHOOK_SECRET","STRIPE_PUBLISHABLE_KEY","STRIPE_SECRET_KEY","STRIPE_WEBHOOK_SECRET","PAYPAL_CLIENT_ID","PAYPAL_CLIENT_SECRET","GOOGLE_CLIENT_ID","GOOGLE_CLIENT_SECRET","ZOOM_ACCOUNT_ID","ZOOM_CLIENT_ID","ZOOM_CLIENT_SECRET","SMTP_HOST","SMTP_PORT","SMTP_USER","SMTP_PASSWORD","SMTP_FROM_EMAIL","BREVO_API_KEY","MSG91_AUTH_KEY","MSG91_SENDER_ID","MSG91_REMINDER_TEMPLATE_ID","WHATSAPP_PHONE_ID","WHATSAPP_BUSINESS_ID","WHATSAPP_ACCESS_TOKEN","WHATSAPP_REMINDER_TEMPLATE","GA4_MEASUREMENT_ID","META_PIXEL_ID","LINKEDIN_PARTNER_ID","RECAPTCHA_SITE_KEY","RECAPTCHA_SECRET_KEY","CLOUDINARY_CLOUD_NAME","CLOUDINARY_API_KEY","CLOUDINARY_API_SECRET","AWS_ACCESS_KEY_ID","AWS_SECRET_ACCESS_KEY","AWS_REGION","AWS_S3_BUCKET"]);
export const secretGroups=[
 {name:"Payments",description:"Payment collection and signed webhook verification.",fields:[["RAZORPAY_KEY_ID","Razorpay Key ID"],["RAZORPAY_KEY_SECRET","Razorpay Key Secret"],["RAZORPAY_WEBHOOK_SECRET","Razorpay Webhook Secret"],["STRIPE_PUBLISHABLE_KEY","Stripe Publishable Key"],["STRIPE_SECRET_KEY","Stripe Secret Key"],["STRIPE_WEBHOOK_SECRET","Stripe Webhook Secret"],["PAYPAL_CLIENT_ID","PayPal Client ID"],["PAYPAL_CLIENT_SECRET","PayPal Client Secret"]]},
 {name:"Login & meetings",description:"External sign-in and online consultation providers.",fields:[["GOOGLE_CLIENT_ID","Google Client ID"],["GOOGLE_CLIENT_SECRET","Google Client Secret"],["ZOOM_ACCOUNT_ID","Zoom Account ID"],["ZOOM_CLIENT_ID","Zoom Client ID"],["ZOOM_CLIENT_SECRET","Zoom Client Secret"]]},
 {name:"Email, SMS & WhatsApp",description:"Transactional alerts, reminders and customer communication.",fields:[["SMTP_HOST","SMTP Host"],["SMTP_PORT","SMTP Port"],["SMTP_USER","SMTP Username"],["SMTP_PASSWORD","SMTP Password"],["SMTP_FROM_EMAIL","From Email"],["BREVO_API_KEY","Brevo API Key"],["MSG91_AUTH_KEY","MSG91 Auth Key"],["MSG91_SENDER_ID","MSG91 Sender ID"],["MSG91_REMINDER_TEMPLATE_ID","MSG91 Reminder Template ID"],["WHATSAPP_PHONE_ID","WhatsApp Phone ID"],["WHATSAPP_BUSINESS_ID","WhatsApp Business ID"],["WHATSAPP_ACCESS_TOKEN","WhatsApp Access Token"],["WHATSAPP_REMINDER_TEMPLATE","WhatsApp Reminder Template Name"]]},
 {name:"Analytics & security",description:"Tracking, attribution and anti-spam services.",fields:[["GA4_MEASUREMENT_ID","Google Analytics ID"],["META_PIXEL_ID","Meta Pixel ID"],["LINKEDIN_PARTNER_ID","LinkedIn Partner ID"],["RECAPTCHA_SITE_KEY","reCAPTCHA Site Key"],["RECAPTCHA_SECRET_KEY","reCAPTCHA Secret Key"]]},
 {name:"Media & storage",description:"External media optimisation and cloud file storage.",fields:[["CLOUDINARY_CLOUD_NAME","Cloudinary Cloud Name"],["CLOUDINARY_API_KEY","Cloudinary API Key"],["CLOUDINARY_API_SECRET","Cloudinary API Secret"],["AWS_ACCESS_KEY_ID","AWS Access Key ID"],["AWS_SECRET_ACCESS_KEY","AWS Secret Access Key"],["AWS_REGION","AWS Region"],["AWS_S3_BUCKET","S3 Bucket"]]},
] as const;
function bytesToB64(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}function b64ToBytes(s:string){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function runtime(){return(await import("cloudflare:workers")).env as Runtime}
async function key(e:Runtime){if(!e.SETTINGS_ENCRYPTION_KEY)throw new Error("Credential vault is not configured.");const raw=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(e.SETTINGS_ENCRYPTION_KEY));return crypto.subtle.importKey("raw",raw,"AES-GCM",false,["encrypt","decrypt"])}
export async function ensureVault(){const e=await runtime();await e.DB.batch([e.DB.prepare("CREATE TABLE IF NOT EXISTS integration_secrets(key TEXT PRIMARY KEY,cipher_text TEXT NOT NULL,iv TEXT NOT NULL,updated_by TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),e.DB.prepare("CREATE INDEX IF NOT EXISTS integration_secrets_updated_idx ON integration_secrets(updated_at)")]);return e}
export async function saveSecret(name:string,value:string,actor:string){if(!allowed.has(name))throw new Error("Unsupported credential field.");const e=await ensureVault(),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},await key(e),new TextEncoder().encode(value));await e.DB.prepare("INSERT INTO integration_secrets(key,cipher_text,iv,updated_by) VALUES (?,?,?,?) ON CONFLICT(key) DO UPDATE SET cipher_text=excluded.cipher_text,iv=excluded.iv,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP").bind(name,bytesToB64(new Uint8Array(cipher)),bytesToB64(iv),actor).run()}
export async function readSecret(name:string){if(!allowed.has(name))return undefined;const e=await ensureVault(),row=await e.DB.prepare("SELECT cipher_text AS cipherText,iv FROM integration_secrets WHERE key=?").bind(name).first<{cipherText:string;iv:string}>();if(!row)return undefined;try{const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:b64ToBytes(row.iv)},await key(e),b64ToBytes(row.cipherText));return new TextDecoder().decode(plain)}catch{return undefined}}
export async function secretStatuses(){const e=await ensureVault(),rows=await e.DB.prepare("SELECT key,updated_by AS updatedBy,updated_at AS updatedAt FROM integration_secrets ORDER BY key").all<{key:string;updatedBy:string;updatedAt:string}>();return rows.results}
