"use client";
import{FormEvent,useEffect,useState}from"react";
type Course={id:number;title:string;slug:string;category:string;level:string;mode:string;duration:string;description:string;price:number;lessons:number;status:string;imageUrl:string;instructor:string;certificate:number;showInShop:number;metaTitle:string;metaKeywords:string;metaDescription:string};
const tabs=[["general","General"],["curriculum","Curriculum"],["pricing","Pricing"],["media","Media"],["visibility","Visibility"],["seo","SEO"]];
export default function CourseEditor({id}:{id?:number}){
 const[tab,setTab]=useState("general"),[course,setCourse]=useState<Course|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(Boolean(id));
 useEffect(()=>{if(!id)return;fetch("/api/admin/learning").then(async r=>{const d=await r.json();const found=(d.courses??[]).find((x:Course)=>x.id===id);if(found)setCourse(found);else setMessage("Course not found.");setBusy(false)})},[id]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/admin/learning",{method:id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,...(id?{id,kind:"course"}:{})})});const d=await r.json();if(r.ok)window.location.href="/admin?module=courses";else{setMessage(d.error||"Unable to save course.");setBusy(false)}}
 if(busy&&id&&!course)return <main className="catalog-editor-shell"><div className="editor-loading">Loading course editor…</div></main>;
 const c=course;
 return <main className="catalog-editor-shell"><header className="editor-topbar"><div><a href="/admin?module=courses">← Courses</a><p>ATTRI ACADEMY / COURSE CATALOGUE</p><h1>{id?"Edit course":"Add course"}</h1></div><a href="/courses" target="_blank">View courses ↗</a></header>{message&&<div className="editor-message">{message}</div>}
  <form className="catalog-editor" key={c?.id??"new"} onSubmit={save}><nav className="editor-tabs">{tabs.map(([key,label])=><button type="button" className={tab===key?"active":""} onClick={()=>setTab(key)} key={key}>{label}</button>)}</nav><div className="editor-body">
   <section className={tab==="general"?"editor-panel active":"editor-panel"}><h2>General information</h2><p>Course identity, audience and delivery format.</p><div className="editor-grid"><label className="wide">Course title<input name="title" required defaultValue={c?.title}/></label><label>Category<select name="category" defaultValue={c?.category||"Vastu Shastra"}><option>Vastu Shastra</option><option>Architecture</option><option>Interior Design</option><option>Structural Design</option><option>Construction</option><option>Professional</option></select></label><label>Level<select name="level" defaultValue={c?.level||"Beginner"}><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>Professional</option></select></label><label>Course type<select name="mode" defaultValue={c?.mode||"Recorded"}><option>Recorded</option><option>Live</option><option>Live + Recorded</option><option>Offline</option></select></label><label>Instructor<input name="instructor" required defaultValue={c?.instructor||"Attri Academy Faculty"}/></label><label className="wide">Description<textarea name="description" rows={8} required defaultValue={c?.description}/></label></div></section>
   <section className={tab==="curriculum"?"editor-panel active":"editor-panel"}><h2>Curriculum</h2><p>Define the length and learning structure.</p><div className="editor-grid"><label>Duration<input name="duration" required defaultValue={c?.duration} placeholder="8 weeks"/></label><label>Lessons / classes<input name="lessons" type="number" min="0" required defaultValue={c?.lessons??0}/></label><label>Certificate<select name="certificate" defaultValue={c?.certificate===0?"no":"yes"}><option value="yes">Included</option><option value="no">Not included</option></select></label></div></section>
   <section className={tab==="pricing"?"editor-panel active":"editor-panel"}><h2>Course pricing</h2><p>Use zero for a free programme.</p><div className="editor-grid"><label>Price (₹)<input name="price" type="number" min="0" step=".01" required defaultValue={c?c.price/100:0}/></label></div></section>
   <section className={tab==="media"?"editor-panel active":"editor-panel"}><h2>Course media</h2><p>Add a strong programme cover image.</p><div className="editor-grid"><label className="wide">Course image URL<input name="imageUrl" type="url" defaultValue={c?.imageUrl} placeholder="https://..."/></label>{c?.imageUrl&&<img className="editor-image-preview" src={c.imageUrl} alt="Current course"/>}</div></section>
   <section className={tab==="visibility"?"editor-panel active":"editor-panel"}><h2>Publishing</h2><p>Control course and Shop visibility.</p><div className="editor-grid"><label>Status<select name="status" defaultValue={c?.status||"draft"}><option value="published">Published — live</option><option value="draft">Draft — hidden</option></select></label><label>Show in Shop<select name="showInShop" defaultValue={c?.showInShop===0?"no":"yes"}><option value="yes">Yes</option><option value="no">No</option></select></label></div></section>
   <section className={tab==="seo"?"editor-panel active":"editor-panel"}><h2>Search engine optimization</h2><p>Configure the course URL and search result copy.</p><div className="editor-grid"><label className="wide">URL slug<div className="slug-input"><span>/courses/</span><input name="slug" defaultValue={c?.slug} placeholder="auto-created-from-course-title"/></div></label><label className="wide">Meta title<input name="metaTitle" maxLength={70} defaultValue={c?.metaTitle}/></label><label className="wide">Meta keywords<input name="metaKeywords" defaultValue={c?.metaKeywords} placeholder="vastu course, architecture training, online certification"/></label><label className="wide">Meta description<textarea name="metaDescription" maxLength={170} rows={4} defaultValue={c?.metaDescription}/></label></div></section>
  </div><footer className="editor-actions"><a href="/admin?module=courses">Cancel</a><button disabled={busy}>{busy?"Saving…":id?"Save changes":"Create course"}</button></footer></form>
 </main>
}
