"use client";
import { FormEvent, useEffect, useState } from "react";
export default function SecurityClient() {
  const [account, setAccount] = useState<any>(null), [sessions, setSessions] = useState(0), [message, setMessage] = useState(""), [error, setError] = useState("");
  useEffect(() => { fetch("/api/auth/security").then(response => response.json()).then(data => { if (data.account) { setAccount(data.account); setSessions(data.activeSessions); } }); }, []);
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); setError(""); const values = new FormData(event.currentTarget); if (values.get("newPassword") !== values.get("confirmPassword")) { setError("New passwords do not match."); return; } const response = await fetch("/api/auth/security", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ currentPassword: values.get("currentPassword"), newPassword: values.get("newPassword") }) }); const data = await response.json(); if (response.ok) window.location.replace(data.destination); else setError(data.error || "Unable to change password."); }
  async function logoutAll() { const response = await fetch("/api/auth/security", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "logout-all" }) }); const data = await response.json(); if (response.ok) window.location.replace(data.destination); else setMessage("Unable to close sessions."); }
  return <main className="security-page"><header><a className="brand" href="/"><span className="brand-mark">A</span><span><strong>ATTRI</strong><small>ACCOUNT SECURITY</small></span></a><a href={account?.accountType === "admin" ? "/admin" : account?.accountType === "consultant" ? "/consultant" : "/client"}>Return to dashboard →</a></header><section><div className="security-summary"><p>ACCOUNT PROTECTION</p><h1>Security<br/><em>centre.</em></h1><span>Review your account and protect access to your Attri workspace.</span><dl><div><dt>Email</dt><dd>{account?.email || "Loading…"}</dd></div><div><dt>Account type</dt><dd>{account?.accountType || "—"}</dd></div><div><dt>Active sessions</dt><dd>{sessions}</dd></div><div><dt>Last login</dt><dd>{account?.lastLoginAt?.slice(0, 16) || "First session"}</dd></div></dl><button onClick={logoutAll}>Sign out everywhere</button></div><form className="security-password-form" onSubmit={changePassword}><p>CHANGE PASSWORD</p><h2>Update your password</h2><label>Current password<input name="currentPassword" type="password" required autoComplete="current-password" /></label><label>New password<input name="newPassword" type="password" required minLength={10} autoComplete="new-password" placeholder="Uppercase, lowercase, number, 10+ characters" /></label><label>Confirm new password<input name="confirmPassword" type="password" required minLength={10} autoComplete="new-password" /></label>{error && <div className="registration-error">{error}</div>}{message && <div>{message}</div>}<button>Change password & close sessions →</button></form></section></main>;
}
