"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
type Product={id:number;name:string;category:string;description:string;price:number;stock:number};
export default function ShopClient(){
 const[products,setProducts]=useState<Product[]>([]);const[cart,setCart]=useState<Record<number,number>>({});const[category,setCategory]=useState("All");const[checkout,setCheckout]=useState(false);const[result,setResult]=useState("");
 useEffect(()=>{fetch("/api/shop").then(r=>r.json()).then(d=>setProducts(d.products??[]))},[]);
 const visible=category==="All"?products:products.filter(x=>x.category===category);const count=Object.values(cart).reduce((a,b)=>a+b,0);const total=products.reduce((s,p)=>s+(cart[p.id]??0)*p.price,0);
 const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v/100);
 async function order(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const body={...Object.fromEntries(new FormData(form)),items:Object.entries(cart).map(([id,quantity])=>({id:Number(id),quantity}))};const r=await fetch("/api/shop",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(r.ok){setResult(d.reference);setCart({})}else alert(d.error)}
 if(result)return <div className="order-success"><span>✓</span><h2>Order request received.</h2><strong>{result}</strong><p>Our team will contact you to confirm availability, shipping and payment.</p><button onClick={()=>setResult("")}>Continue shopping</button></div>;
 return <><div className="shop-toolbar"><div>{["All","Tools","Remedies","Reports","Books","Software"].map(x=><button className={category===x?"active":""} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><button className="cart-button" onClick={()=>setCheckout(!checkout)}>Bag · {count} <span>{money(total)}</span></button></div>
 <div className="product-grid">{visible.map((p,i)=><article key={p.id}><div className={`product-art art-${i%6}`}><span>{p.category}</span><b>{["✦","◈","⌁","▤","△","A"][i%6]}</b></div><div><small>{p.category}</small><h3>{p.name}</h3><p>{p.description}</p><footer><strong>{money(p.price)}</strong><button onClick={()=>setCart(c=>({...c,[p.id]:(c[p.id]??0)+1}))}>Add +</button></footer></div></article>)}</div>
 {checkout&&<div className="checkout-drawer"><button className="drawer-close" onClick={()=>setCheckout(false)}>×</button><p>YOUR ORDER</p><h2>Review & request</h2>{products.filter(p=>cart[p.id]).map(p=><div className="cart-line" key={p.id}><span><b>{p.name}</b><small>{money(p.price)} × {cart[p.id]}</small></span><button onClick={()=>setCart(c=>{const n={...c};delete n[p.id];return n})}>Remove</button></div>)}<div className="cart-total"><span>Subtotal</span><b>{money(total)}</b></div><form onSubmit={order}><input name="name" required placeholder="Full name"/><input name="phone" required placeholder="Phone"/><input name="email" required type="email" placeholder="Email"/><textarea name="address" required placeholder="Delivery address"/><div><input name="city" required placeholder="City"/><input name="state" required placeholder="State"/></div><input name="pincode" required placeholder="PIN code"/><button disabled={!count}>Place order request</button></form><small>Payment will be enabled after gateway configuration. No online payment is collected now.</small></div>}
 </>;
}
