"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
type Product={id:number;name:string;slug?:string;category:string;description:string;shortDescription?:string;price:number;regularPrice?:number;stock:number;imageUrl:string;kind?:string;itemType?:string;deliveryMode?:string;duration?:string;classes?:number;serviceType?:string;fulfillmentMode?:string;sku?:string;material?:string};
export default function ShopClient(){
 const[products,setProducts]=useState<Product[]>([]);const[cart,setCart]=useState<Record<number,number>>({});const[category,setCategory]=useState("All");const[checkout,setCheckout]=useState(false);const[step,setStep]=useState(1);const[result,setResult]=useState<{reference:string;total:number;paymentMethod:string}|null>(null);
 useEffect(()=>{fetch("/api/shop").then(r=>r.json()).then(d=>setProducts([...(d.products??[]),...(d.courses??[]).map((x:Product)=>({...x,id:-x.id,kind:"course"}))]));try{setCart(JSON.parse(localStorage.getItem("attri-cart")||"{}"))}catch{}if(new URLSearchParams(window.location.search).get("cart")==="open")setCheckout(true)},[]);
 useEffect(()=>{localStorage.setItem("attri-cart",JSON.stringify(cart));window.dispatchEvent(new Event("attri-cart"))},[cart]);
 const visible=category==="All"?products:products.filter(x=>x.category===category);const count=Object.values(cart).reduce((a,b)=>a+b,0);const subtotal=products.reduce((s,p)=>s+(cart[p.id]??0)*p.price,0);const shipping=subtotal>=500000||subtotal===0?0:19900;const total=subtotal+shipping;
 const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v/100);
 async function order(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const body={...Object.fromEntries(new FormData(form)),items:Object.entries(cart).map(([id,quantity])=>({id:Number(id),quantity}))};const r=await fetch("/api/shop",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(r.ok){setResult(d);setCart({})}else alert(d.error)}
 if(result)return <div className="order-success"><span>✓</span><h2>Your order is confirmed.</h2><strong>{result.reference}</strong><p>Total: {money(result.total)} · {result.paymentMethod==="bank-upi-transfer"?"Bank/UPI transfer selected":"Payment after confirmation"}</p><p>You can follow its status from your client portal using the same email address.</p><button onClick={()=>{setResult(null);setCheckout(false);setStep(1)}}>Continue shopping</button></div>;
 const categories=["All",...Array.from(new Set(products.map(x=>x.category)))];
 return <><div className="shop-toolbar"><div>{categories.map(x=><button className={category===x?"active":""} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><button className="cart-button" onClick={()=>setCheckout(!checkout)}>Bag · {count} <span>{money(subtotal)}</span></button></div>
 <div className="product-grid">{visible.map((p,i)=><article key={`${p.kind||"product"}-${p.id}`}><div className={`product-art art-${i%6}`}>{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<b>{["✦","◈","⌁","▤","△","A"][i%6]}</b>}<span>{p.itemType==="service"?(p.serviceType==="consultation"?"Consultation":"Virtual service"):p.category}</span></div><div><small>{p.category}{p.fulfillmentMode?` · Delivered via ${p.fulfillmentMode}`:p.deliveryMode?` · ${p.deliveryMode}`:""}</small><h3>{p.name}</h3><p>{p.shortDescription||p.description}</p>{p.itemType==="course"&&<div className="course-meta"><span>{p.duration}</span><span>{p.classes} classes</span></div>}{p.itemType==="service"&&<div className="course-meta"><span>{p.serviceType==="consultation"?"Appointment based":"Virtual delivery"}</span><span>{p.fulfillmentMode||"Online"}</span></div>}{p.kind!=="course"&&p.slug&&<a className="product-detail-link" href={`/shop/${p.slug}`}>View details →</a>}<footer><strong>{p.regularPrice&&p.regularPrice!==p.price?<><del>{money(p.regularPrice)}</del> {money(p.price)}</>:money(p.price)}</strong>{p.kind==="course"?<a className="shop-course-link" href="/courses">View course →</a>:p.itemType==="service"&&p.serviceType==="consultation"?<a className="shop-course-link service-book-link" href="/book-consultation">Book consultation →</a>:<button disabled={p.stock<1} onClick={()=>setCart(c=>({...c,[p.id]:(c[p.id]??0)+1}))}>{p.stock<1?"Unavailable":"Add +"}</button>}</footer></div></article>)}</div>
 {checkout&&<div className="checkout-drawer commerce-checkout"><button className="drawer-close" onClick={()=>setCheckout(false)}>×</button><p>SECURE CHECKOUT</p><h2>{step===1?"Review your bag":"Delivery & payment"}</h2><div className="checkout-steps"><span className={step===1?"active":"done"}>1 · Bag</span><span className={step===2?"active":""}>2 · Details</span></div>{step===1?<>{products.filter(p=>cart[p.id]).map(p=><div className="cart-line" key={p.id}><span><b>{p.name}</b><small>{money(p.price)} each</small></span><div className="cart-quantity"><button onClick={()=>setCart(c=>({...c,[p.id]:Math.max(1,(c[p.id]||1)-1)}))}>−</button><b>{cart[p.id]}</b><button onClick={()=>setCart(c=>({...c,[p.id]:Math.min(p.stock,(c[p.id]||0)+1)}))}>+</button><button onClick={()=>setCart(c=>{const n={...c};delete n[p.id];return n})}>Remove</button></div></div>)}{!count&&<p className="empty-cart">Your bag is empty.</p>}<div className="checkout-totals"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Shipping</span><b>{shipping?money(shipping):"Free"}</b></div><div><span>Order total</span><b>{money(total)}</b></div></div><small>Free delivery on orders of ₹5,000 or more.</small><button className="checkout-next" disabled={!count} onClick={()=>setStep(2)}>Continue to details →</button></>:<form onSubmit={order}><button type="button" className="checkout-back" onClick={()=>setStep(1)}>← Edit bag</button><input name="name" required placeholder="Full name"/><input name="phone" required placeholder="Phone number"/><input name="email" required type="email" placeholder="Email for order updates"/><textarea name="address" required placeholder="Complete delivery address"/><div><input name="city" required placeholder="City"/><input name="state" required placeholder="State"/></div><input name="pincode" required inputMode="numeric" pattern="[0-9]{6}" placeholder="6-digit PIN code"/><fieldset><legend>Payment preference</legend><label><input type="radio" name="paymentMethod" value="pay-after-confirmation" defaultChecked/><span><b>Pay after confirmation</b><small>Our team confirms availability before payment.</small></span></label><label><input type="radio" name="paymentMethod" value="bank-upi-transfer"/><span><b>Bank / UPI transfer</b><small>Payment instructions are shared securely after order review.</small></span></label></fieldset><div className="checkout-payable"><span>Amount payable</span><b>{money(total)}</b></div><button disabled={!count}>Place secure order</button><small>Razorpay and card payments will activate after merchant credentials are connected. No card details are collected here.</small></form>}</div>}
 </>;
}
