import{getChatGPTUser}from"../../chatgpt-auth";const db = () => runtimeEnv.DB;
import { env as runtimeEnv } from "@server";
async function user(){return await getChatGPTUser()}
async function init(){const d=await db();await d.batch([
 d.prepare(`CREATE TABLE IF NOT EXISTS support_tickets (id INTEGER PRIMARY KEY AUTOINCREMENT,reference TEXT NOT NULL UNIQUE,customer_email TEXT NOT NULL,subject TEXT NOT NULL,category TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',priority TEXT NOT NULL DEFAULT 'normal',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS customer_profiles (id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT NOT NULL UNIQUE,full_name TEXT NOT NULL,phone TEXT NOT NULL DEFAULT '',company TEXT NOT NULL DEFAULT '',address TEXT NOT NULL DEFAULT '',city TEXT NOT NULL DEFAULT '',state TEXT NOT NULL DEFAULT '',pincode TEXT NOT NULL DEFAULT '',gstin TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS order_events (id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,status TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 d.prepare(`CREATE TABLE IF NOT EXISTS portal_notifications (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,message TEXT NOT NULL,audience TEXT NOT NULL DEFAULT 'all',recipient_email TEXT NOT NULL DEFAULT '',severity TEXT NOT NULL DEFAULT 'info',action_url TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'published',expires_at TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`)
]);const columns=await d.prepare("PRAGMA table_info(customer_profiles)").all<{name:string}>();if(!columns.results.some(x=>x.name==="account_type"))await d.prepare("ALTER TABLE customer_profiles ADD COLUMN account_type TEXT NOT NULL DEFAULT ''").run();if(!columns.results.some(x=>x.name==="registration_completed"))await d.prepare("ALTER TABLE customer_profiles ADD COLUMN registration_completed INTEGER NOT NULL DEFAULT 0").run()}
export async function GET(){
 const u=await user();if(!u)return Response.json({error:"Unauthorized"},{status:401});await init();const d=await db();const email=u.email.toLowerCase();
 const profile=await d.prepare("SELECT account_type AS accountType,registration_completed AS registrationCompleted,status FROM customer_profiles WHERE lower(email)=?").bind(email).first<{accountType:string;registrationCompleted:number;status:string}>();if(profile?.accountType!=="user"||profile.registrationCompleted!==1||profile.status!=="active")return Response.json({error:"This dashboard requires a User account."},{status:403});
 await d.prepare(`INSERT INTO customer_profiles (email,full_name,status) VALUES (?,?, 'active')
  ON CONFLICT(email) DO UPDATE SET full_name=excluded.full_name,updated_at=CURRENT_TIMESTAMP`).bind(email,u.fullName||u.displayName).run();
 const [appointments,orders,enrollments,tickets,invoices,reports,certificates,payments,files]=await Promise.all([
  d.prepare("SELECT id,reference,service,consultation_mode AS consultationMode,preferred_date AS preferredDate,preferred_time AS preferredTime,status,consultant_preference AS consultantPreference,meeting_url AS meetingUrl,created_at AS createdAt FROM appointments WHERE lower(email)=? ORDER BY created_at DESC").bind(email).all(),
  d.prepare("SELECT id,reference,CASE WHEN total>0 THEN total ELSE subtotal END AS total,status,payment_status AS paymentStatus,tracking_number AS trackingNumber,created_at AS createdAt FROM orders WHERE lower(email)=? ORDER BY created_at DESC").bind(email).all(),
  d.prepare("SELECT e.reference,c.title AS courseTitle,e.status,e.payment_status AS paymentStatus,e.progress,e.created_at AS createdAt FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE lower(e.email)=? ORDER BY e.created_at DESC").bind(email).all(),
  d.prepare("SELECT reference,subject,category,status,priority,created_at AS createdAt FROM support_tickets WHERE lower(customer_email)=? ORDER BY created_at DESC").bind(email).all(),
  d.prepare("SELECT number,description,amount,tax_rate AS taxRate,status,due_date AS dueDate,created_at AS createdAt FROM invoices WHERE lower(customer_email)=? ORDER BY created_at DESC").bind(email).all(),
  d.prepare("SELECT reference,title,report_type AS reportType,summary,status,created_at AS createdAt FROM client_reports WHERE lower(customer_email)=? AND status='published' ORDER BY created_at DESC").bind(email).all(),
  d.prepare("SELECT reference,course_title AS courseTitle,issued_date AS issuedDate,status FROM certificates WHERE lower(student_email)=? AND status='issued' ORDER BY created_at DESC").bind(email).all(),
  d.prepare("SELECT reference,purpose,gateway,transaction_id AS transactionId,amount,status,created_at AS createdAt FROM payment_records WHERE lower(customer_email)=? ORDER BY created_at DESC").bind(email).all(),
  d.prepare("SELECT reference,file_name AS fileName,content_type AS contentType,size,category,created_at AS createdAt FROM client_files WHERE lower(customer_email)=? ORDER BY created_at DESC").bind(email).all()
 ]);const events=await d.prepare("SELECT e.order_id AS orderId,e.status,e.note,e.created_at AS createdAt FROM order_events e JOIN orders o ON o.id=e.order_id WHERE lower(o.email)=? ORDER BY e.created_at DESC").bind(email).all<{orderId:number;status:string;note:string;createdAt:string}>();const eventMap=new Map<number,unknown[]>();for(const event of events.results){const list=eventMap.get(event.orderId)||[];list.push(event);eventMap.set(event.orderId,list)}const enrichedOrders=(orders.results as Array<{id:number}>).map(order=>({...order,events:eventMap.get(order.id)||[]}));return Response.json({profile:{name:u.displayName,email:u.email},appointments:appointments.results,orders:enrichedOrders,enrollments:enrollments.results,tickets:tickets.results,invoices:invoices.results,reports:reports.results,certificates:certificates.results,payments:payments.results,files:files.results})
}
export async function POST(request:Request){const u=await user();if(!u)return Response.json({error:"Unauthorized"},{status:401});const b=await request.json()as Record<string,string>;await init();const d=await db();
 if(b.action==="cancel-appointment"){const id=Number(b.id);if(!id)return Response.json({error:"Appointment is required."},{status:400});const appointment=await d.prepare("SELECT id,reference,email,status FROM appointments WHERE id=? AND lower(email)=?").bind(id,u.email.toLowerCase()).first<{id:number;reference:string;email:string;status:string}>();if(!appointment)return Response.json({error:"Appointment not found."},{status:404});if(!["pending","confirmed"].includes(appointment.status))return Response.json({error:"This appointment can no longer be cancelled."},{status:409});await d.prepare("UPDATE appointments SET status='cancelled' WHERE id=?").bind(id).run();await d.prepare("CREATE TABLE IF NOT EXISTS portal_notifications (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,message TEXT NOT NULL,audience TEXT NOT NULL DEFAULT 'all',recipient_email TEXT NOT NULL DEFAULT '',severity TEXT NOT NULL DEFAULT 'info',action_url TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'published',expires_at TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();await d.prepare("INSERT INTO portal_notifications(title,message,audience,recipient_email,severity,action_url) VALUES (?,?,?,?,?,?)").bind("Consultation cancelled",`Your consultation ${appointment.reference} was cancelled successfully.`,`individual`,u.email.toLowerCase(),"info","/client").run();return Response.json({success:true,reference:appointment.reference})}
 if(!b.subject||!b.category||!b.message)return Response.json({error:"Complete all ticket fields."},{status:400});const profile=await d.prepare("SELECT account_type AS accountType,registration_completed AS registrationCompleted,status FROM customer_profiles WHERE lower(email)=?").bind(u.email.toLowerCase()).first<{accountType:string;registrationCompleted:number;status:string}>();if(profile?.accountType!=="user"||profile.registrationCompleted!==1||profile.status!=="active")return Response.json({error:"This action requires a User account."},{status:403});const reference=`SUP-${Date.now().toString(36).toUpperCase()}`;await d.prepare("INSERT INTO support_tickets (reference,customer_email,subject,category,message,priority) VALUES (?,?,?,?,?,?)").bind(reference,u.email,b.subject.trim(),b.category,b.message.trim(),b.priority||"normal").run();return Response.json({success:true,reference},{status:201})}
