"use client";
import {FormEvent,useEffect,useState} from "react";
type Package={slug:string;name:string;price:number;duration:number;summary:string;modes:string[]};type PayResult={razorpay_payment_id:string;razorpay_order_id:string;razorpay_signature:string};
declare global{interface Window{Razorpay:new(o:any)=>{open:()=>void;on:(e:string,c:(x:any)=>void)=>void}}}
async function loadRazorpay(){if(window.Razorpay)return true;return new Promise<boolean>(resolve=>{const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.async=true;s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
export default function BookingForm(){const[packages,setPackages]=useState<Package[]>([]),[selected,setSelected]=useState("scientific-vastu"),[date,setDate]=useState(""),[slots,setSlots]=useState<string[]>([]),[booked,setBooked]=useState<string[]>([]),[result,setResult]=useState<{reference?:string;error?:string}|null>(null),[busy,setBusy]=useState(false);const pkg=packages.find(x=>x.slug===selected);
 useEffect(()=>{fetch("/api/consultations/catalog").then(r=>r.json()).then(d=>{setPackages(d.packages||[]);setSlots(d.slots||[])})},[]);useEffect(()=>{if(date)fetch(`/api/consultations/catalog?date=${date}`).then(r=>r.json()).then(d=>{setSlots(d.slots||[]);setBooked(d.booked||[])})},[date]);
 const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v/100);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setResult(null);const loaded=await loadRazorpay();if(!loaded){setResult({error:"Secure checkout could not load. Please try again."});setBusy(false);return}const body={...Object.fromEntries(new FormData(event.currentTarget)),packageSlug:selected};const r=await fetch("/api/payments/razorpay/consultation/order",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(r.status===401){window.location.href=`/client/login?returnTo=${encodeURIComponent("/book-consultation")}`;return}if(!r.ok){setResult({error:d.error});setBusy(false);return}const gateway=new window.Razorpay({key:d.keyId,amount:d.amount,currency:d.currency,name:"Attri Associates",description:d.description,order_id:d.orderId,prefill:d.prefill,theme:{color:"#ed7a22",backdrop_color:"#180e23"},modal:{ondismiss:()=>{setResult({error:"Payment window closed. Your slot is held briefly; you can try again."});setBusy(false)}},handler:async(payment:PayResult)=>{const v=await fetch("/api/payments/razorpay/consultation/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payment)}),c=await v.json();if(v.ok&&!c.pending){setResult({reference:c.reference});setBusy(false)}else{setResult({error:c.message||c.error||"Payment is awaiting confirmation."});setBusy(false)}}});gateway.on("payment.failed",(x:any)=>{setResult({error:x.error?.description||"Payment was not completed."});setBusy(false)});gateway.open()}
 if(result?.reference)return <div className="booking-success"><span>✓</span><p>PAYMENT RECEIVED</p><h2>Your consultation is confirmed.</h2><strong>{result.reference}</strong><p>The appointment and GST invoice are now available in your client portal.</p><a href="/client">Open client portal →</a></div>;
 return <form className="booking-form" onSubmit={submit}><div className="form-section"><span>01</span><div><h3>Select a consultation package</h3><p>Choose a clearly priced session before selecting your schedule.</p></div></div><div className="consultation-package-grid">{packages.map(x=><button type="button" key={x.slug} className={selected===x.slug?"active":""} onClick={()=>setSelected(x.slug)}><small>{x.duration} MINUTES</small><b>{x.name}</b><p>{x.summary}</p><strong>{money(x.price)}</strong></button>)}</div>
 <div className="form-section"><span>02</span><div><h3>Choose mode and schedule</h3><p>Unavailable times are disabled automatically.</p></div></div><div className="booking-grid"><label>Consultation mode *<select name="consultationMode" required><option value="">Select mode</option>{pkg?.modes.map(x=><option key={x}>{x}</option>)}</select></label><label>Project type<select name="projectType"><option>New Construction</option><option>Existing Property</option><option>Renovation</option><option>Drawing Review</option></select></label><label>Preferred date *<input type="date" name="preferredDate" required value={date} onChange={e=>setDate(e.target.value)} min={new Date().toISOString().slice(0,10)}/></label><label>Preferred time *<select name="preferredTime" required><option value="">Select available time</option>{slots.map(x=><option key={x} disabled={booked.includes(x)} value={x}>{x}{booked.includes(x)?" · Booked":""}</option>)}</select></label></div>
 <div className="form-section"><span>03</span><div><h3>Your information</h3><p>Your registered account email will receive the confirmation and invoice.</p></div></div><div className="booking-grid two"><label>Full name *<input name="name" required/></label><label>Phone number *<input name="phone" required inputMode="tel"/></label></div><label className="message-field">Tell us about your requirement<textarea name="message" rows={5} placeholder="Property type, location, approximate area and the guidance you need"/></label>{result?.error&&<p className="booking-error">{result.error}</p>}<div className="consultation-checkout-total"><span>Secure payment</span><strong>{pkg?money(pkg.price):"—"}</strong></div><button className="booking-submit" disabled={busy||!pkg}>{busy?"Preparing payment…":"Pay & confirm consultation"} <span>↗</span></button><div className="razorpay-trust"><span>UPI</span><span>Cards</span><span>Net Banking</span><span>Wallets</span></div><small className="privacy-copy">A registered User account is mandatory. Your booking confirms only after verified Razorpay payment.</small></form>}
